SET GOODEX=
if /I "%ALLEXT%"==".vb" SET GOODEX=1
if /I "%ALLEXT%"==".2D" SET GOODEX=1
if /I "%ALLEXT%"==".st" SET GOODEX=1
if /I "%ALLEXT%"==".vb" SET GOODEX=1
if /I "%ALLEXT%"==".gz" SET GOODEX=1
if /I "%ALLEXT%"==".gg" SET GOODEX=1
if /I "%ALLEXT%"==".md" SET GOODEX=1
if /I "%ALLEXT%"==".gb" SET GOODEX=1
if /I "%ALLEXT%"==".ws" SET GOODEX=1
if /I "%ALLEXT%"==".ds" SET GOODEX=1
if /I "%ALLEXT%"==".a26" SET GOODEX=1
if /I "%ALLEXT%"==".a52" SET GOODEX=1
if /I "%ALLEXT%"==".a78" SET GOODEX=1
if /I "%ALLEXT%"==".adf" SET GOODEX=1
if /I "%ALLEXT%"==".adz" SET GOODEX=1
if /I "%ALLEXT%"==".msa" SET GOODEX=1
if /I "%ALLEXT%"==".fds" SET GOODEX=1
if /I "%ALLEXT%"==".fig" SET GOODEX=1
if /I "%ALLEXT%"==".srm" SET GOODEX=1
if /I "%ALLEXT%"==".swf" SET GOODEX=1
if /I "%ALLEXT%"==".smc" SET GOODEX=1
if /I "%ALLEXT%"==".sfc" SET GOODEX=1
if /I "%ALLEXT%"==".pbp" SET GOODEX=1
if /I "%ALLEXT%"==".cdi" SET GOODEX=1
if /I "%ALLEXT%"==".td0" SET GOODEX=1
if /I "%ALLEXT%"==".sdf" SET GOODEX=1
if /I "%ALLEXT%"==".pgm" SET GOODEX=1
if /I "%ALLEXT%"==".mgt" SET GOODEX=1
if /I "%ALLEXT%"==".j64" SET GOODEX=1
if /I "%ALLEXT%"==".jag" SET GOODEX=1
if /I "%ALLEXT%"==".z26" SET GOODEX=1
if /I "%ALLEXT%"==".rom" SET GOODEX=1
if /I "%ALLEXT%"==".z80" SET GOODEX=1
if /I "%ALLEXT%"==".sbd" SET GOODEX=1
if /I "%ALLEXT%"==".tzx" SET GOODEX=1
if /I "%ALLEXT%"==".lnk" SET GOODEX=1
if /I "%ALLEXT%"==".wad" SET GOODEX=1
if /I "%ALLEXT%"==".cpm" SET GOODEX=1
if /I "%ALLEXT%"==".vec" SET GOODEX=1
if /I "%ALLEXT%"==".sbt" SET GOODEX=1
if /I "%ALLEXT%"==".sgx" SET GOODEX=1
if /I "%ALLEXT%"==".pce" SET GOODEX=1
if /I "%ALLEXT%"==".32x" SET GOODEX=1
if /I "%ALLEXT%"==".pco" SET GOODEX=1
if /I "%ALLEXT%"==".gen" SET GOODEX=1
if /I "%ALLEXT%"==".smd" SET GOODEX=1
if /I "%ALLEXT%"==".prx" SET GOODEX=1
if /I "%ALLEXT%"==".ciso" SET GOODEX=1
if /I "%ALLEXT%"==".cso" SET GOODEX=1
if /I "%ALLEXT%"==".jso" SET GOODEX=1
if /I "%ALLEXT%"==".gbc" SET GOODEX=1
if /I "%ALLEXT%"==".sgb" SET GOODEX=1
if /I "%ALLEXT%"==".gba" SET GOODEX=1
if /I "%ALLEXT%"==".xex" SET GOODEX=1
if /I "%ALLEXT%"==".prg" SET GOODEX=1
if /I "%ALLEXT%"==".atr" SET GOODEX=1
if /I "%ALLEXT%"==".atx" SET GOODEX=1
if /I "%ALLEXT%"==".atz" SET GOODEX=1
if /I "%ALLEXT%"==".dcm" SET GOODEX=1
if /I "%ALLEXT%"==".com" SET GOODEX=1
if /I "%ALLEXT%"==".mx2" SET GOODEX=1
if /I "%ALLEXT%"==".mx1" SET GOODEX=1
if /I "%ALLEXT%"==".xfd" SET GOODEX=1
if /I "%ALLEXT%"==".pro" SET GOODEX=1
if /I "%ALLEXT%"==".bas" SET GOODEX=1
if /I "%ALLEXT%"==".ssd" SET GOODEX=1
if /I "%ALLEXT%"==".uef" SET GOODEX=1
if /I "%ALLEXT%"==".unf" SET GOODEX=1
if /I "%ALLEXT%"==".nsf" SET GOODEX=1
if /I "%ALLEXT%"==".gme" SET GOODEX=1
if /I "%ALLEXT%"==".nes" SET GOODEX=1
if /I "%ALLEXT%"==".fam" SET GOODEX=1
if /I "%ALLEXT%"==".srl" SET GOODEX=1
if /I "%ALLEXT%"==".nds" SET GOODEX=1
if /I "%ALLEXT%"==".fds" SET GOODEX=1
if /I "%ALLEXT%"==".ngp" SET GOODEX=1
if /I "%ALLEXT%"==".npk" SET GOODEX=1
if /I "%ALLEXT%"==".ngc" SET GOODEX=1
if /I "%ALLEXT%"==".neo" SET GOODEX=1
if /I "%ALLEXT%"==".nd5" SET GOODEX=1
if /I "%ALLEXT%"==".pal" SET GOODEX=1
if /I "%ALLEXT%"==".usa" SET GOODEX=1
if /I "%ALLEXT%"==".u64" SET GOODEX=1
if /I "%ALLEXT%"==".j64" SET GOODEX=1
if /I "%ALLEXT%"==".v64" SET GOODEX=1
if /I "%ALLEXT%"==".n64" SET GOODEX=1
if /I "%ALLEXT%"==".z64" SET GOODEX=1
if /I "%ALLEXT%"==".lnx" SET GOODEX=1
if /I "%ALLEXT%"==".int" SET GOODEX=1
if /I "%ALLEXT%"==".tap" SET GOODEX=1
if /I "%ALLEXT%"==".dsk" SET GOODEX=1
if /I "%ALLEXT%"==".sad" SET GOODEX=1
if /I "%ALLEXT%"==".col" SET GOODEX=1
if /I "%ALLEXT%"==".xdf" SET GOODEX=1
if /I "%ALLEXT%"==".dup" SET GOODEX=1
if /I "%ALLEXT%"==".2hd" SET GOODEX=1
if /I "%ALLEXT%"==".ipf" SET GOODEX=1
if /I "%ALLEXT%"==".dim" SET GOODEX=1
if /I "%ALLEXT%"==".fdi" SET GOODEX=1
if /I "%ALLEXT%"==".hdi" SET GOODEX=1
if /I "%ALLEXT%"==".hdf" SET GOODEX=1
if /I "%ALLEXT%"==".nhd" SET GOODEX=1
if /I "%ALLEXT%"==".thd" SET GOODEX=1
if /I "%ALLEXT%"==".hdm" SET GOODEX=1
if /I "%ALLEXT%"==".hds" SET GOODEX=1
if /I "%ALLEXT%"==".d98" SET GOODEX=1
if /I "%ALLEXT%"==".2DD" SET GOODEX=1
if /I "%ALLEXT%"==".vfd" SET GOODEX=1
if /I "%ALLEXT%"==".t77" SET GOODEX=1
if /I "%ALLEXT%"==".d77" SET GOODEX=1
if /I "%ALLEXT%"==".d88" SET GOODEX=1
if /I "%ALLEXT%"==".88d" SET GOODEX=1
if /I "%ALLEXT%"==".wsc" SET GOODEX=1
if /I "%ALLEXT%"==".zip" SET GOODEX=1
if /I "%ALLEXT%"==".vboy" SET GOODEX=1
if /I "%ALLEXT%"==".wbfs" SET GOODEX=1
if /I "%ALLEXT%"==".amiga" SET GOODEX=1