for %%a in ("aMcrCFG") do SET ACONF=%%~a
for %%a in ("Aprofiles") do SET APROF=%%~a
for %%a in ("Banner") do SET BANN=%%~a
for %%a in ("Backdrop") do SET BCKD=%%~a
for %%a in ("BIOS") do SET BIOS=%%~a
for %%a in ("Console") do SET CONS=%%~a
for %%a in ("Conversions") do set CNVRZ=%%~a
for %%a in ("Dropbox") do set DRPBX=%%~a
for %%a in ("DS4Windows") do SET DS4WIN=%%~a
for %%a in ("ConsoleXML") do SET CXML=%%~a
for %%a in ("EmuCfg") do SET ECFG=%%~a
for %%a in ("Emulators") do SET EMUZ=%%~a
for %%a in ("EmuEx") do SET EMEX=%%~a
for %%a in ("Mirrors") do SET MIRZ=%%~a
for %%a in ("HyperMirrors") do SET HYPMIR=%%~a
for %%a in ("Machine") do SET GLBL=%%~a
for %%a in ("Helper") do SET HLPR=%%~a
for %%a in ("Folder") do SET FLDR=%%~a
for %%a in ("Fanart") do SET FNRT=%%~a
for %%a in ("Games") do SET GAM=%%~a
for %%a in ("Launchers") do SET LNCH=%%~a
for %%a in ("plugins") do SET PLGN=%%~a
for %%a in ("rar") do SET RAR=%%~a
for %%a in ("Executables") do set EXECT=%%~a
for %%a in ("RoM-Jacket") do SET ROMJ=%%~a
for %%a in ("vcrs") do SET VCRD=%%~a
for %%a in ("Videos") do SET VIDE=%%~a
for %%a in ("Xprofiles") do SET XPROF=%%~a
for %%a in ("XPadCFG") do SET XCONF=%%~a

for %%a in ("Advanced Launcher") do SET ADVL=%%~a
for %%a in ("antimicro") do SET AMICRO=%%~a
for %%a in ("cabrio") do SET CABR=%%~a
for %%a in ("Daemon Tools") do SET DAEMNT=%%~a
for %%a in ("dxwebsetup") do SET DXWS=%%~a
for %%a in ("emulationStation") do SET EMST=%%~a
for %%a in ("GameEx") do SET GAMEX=%%~a
for %%a in ("GameBrowser") do SET GBRWS=%%~a
for %%a in ("mGalaxy") do SET MGAL=%%~a
for %%a in ("Hyperspin") do SET HYPS=%%~a
for %%a in ("ARCORG") do SET ARCORG=%%~a
for %%a in ("Internet Archive ROM Launcher") do SET IARL=%%~a
for %%a in ("Oblytile") do SET OBLYT=%%~a
for %%a in ("Joy2Key") do SET JOY2K=%%~a
for %%a in ("J2KProfiles") do SET J2KPROF=%%~a
for %%a in ("Kodi") do SET KODI=%%~a
for %%a in ("MediaBrowser") do SET MBRWS=%%~a
for %%a in ("No-Intro-Collection") do set NOINT=%%~a
for %%a in ("PS3Driver") do SET SCPJOY=%%~a
for %%a in ("PS3Driver") do SET PS3JOY=%%~a
for %%a in ("ROMDepot") do SET ROMDPT=%%~a
for %%a in ("Rom Collection Browser") do SET RCBRWS=%%~a
for %%a in ("retroFE") do SET RTFE=%%~a
for %%a in ("x360ce") do SET XBCE=%%~a
for %%a in ("XBoxDriver") do SET XBJOY=%%~a
for %%a in ("XBMC") do SET XBMC=%%~a
for %%a in ("Xpadder") do SET XPADR=%%~a

for %%a in ("Funtech Super A'can") do SET ACAN=%%~a
for %%a in ("Acorn BBC") do SET ACBBC=%%~a
for %%a in ("Acorn Archimedes") do SET ACARC=%%~a
for %%a in ("Acorn Electron") do SET ACELE=%%~a
for %%a in ("Adventure Vision") do SET ADVV=%%~a
for %%a in ("Amstrad CPC") do SET AMSTR=%%~a
for %%a in ("Amstrad GX4000") do SET AMSGX=%%~a
for %%a in ("American Laser Games") do SET AMLG=%%~a
for %%a in ("Commodore Amiga CDTV") do SET AMIGTV=%%~a
for %%a in ("Commodore Amiga CD32") do SET AMIG32=%%~a
for %%a in ("Apple IIe") do SET APL2E=%%~a
for %%a in ("Apple IIgs") do SET APL2GS=%%~a
for %%a in ("Aquarius") do SET AQURS=%%~a
for %%a in ("APF Imagination Machine") do SET APFIM=%%~a
for %%a in ("Arcade") do SET ARCD=%%~a
for %%a in ("Atari 2600") do SET AT26=%%~a
for %%a in ("Atari 5200") do SET AT52=%%~a
for %%a in ("Atari 7800") do SET AT78=%%~a
for %%a in ("Atari 800") do SET AT8H=%%~a
for %%a in ("Atari 8Bit") do SET AT8B=%%~a
for %%a in ("Atari ST") do SET ATST=%%~a
for %%a in ("Atari XE") do SET ATXE=%%~a
for %%a in ("Atomiswave") do SET ATMS=%%~a
for %%a in ("Bally Astrocade") do SET BALY=%%~a
for %%a in ("Bandai Wonder Swan") do SET BWS=%%~a
for %%a in ("Bandai Wonder Swan Color") do SET BWSC=%%~a
for %%a in ("Commodore Amiga") do SET CAMIG=%%~a
for %%a in ("Commodore C128") do SET CC128=%%~a
for %%a in ("Philips CD-I") do SET CDI=%%~a
for %%a in ("Camputers Lynx") do SET CMPLNX=%%~a
for %%a in ("Fairchild Channel F") do SET CHNF=%%~a
for %%a in ("Commodore 64") do SET CM64=%%~a
for %%a in ("Commodore C16") do SET COM16=%%~a
for %%a in ("Commodore PET") do SET CMPET=%%~a
for %%a in ("Commodore MAX") do SET CMMAX=%%~a
for %%a in ("Casio Loopy") do SET CLOOP=%%~a
for %%a in ("Casio PV-1000") do SET CAS1K=%%~a
for %%a in ("Casio PV-2000") do SET CAS2K=%%~a
for %%a in ("ColecoVision") do SET COLEC=%%~a
for %%a in ("Coleco ADAM") do SET COLADM=%%~a
for %%a in ("CPS") do SET CPS=%%~a
for %%a in ("CPS 2") do SET CPS2=%%~a
for %%a in ("CPS 3") do SET CPS3=%%~a
for %%a in ("Daphne") do SET DAPHN=%%~a
for %%a in ("Dragon 32-64") do SET DRAG32=%%~a
for %%a in ("Arcadia 2001") do SET EMARC=%%~a
for %%a in ("Enterprise 128") do SET ENTP128=%%~a
for %%a in ("Enterprise 64") do SET ENTP64=%%~a
for %%a in ("EXL 100") do SET EXL1H=%%~a
for %%a in ("Flash Games") do SET FLASH=%%~a
for %%a in ("FM-7") do SET FM7=%%~a
for %%a in ("FM Towns") do SET FMTOWNS=%%~a
for %%a in ("Game COM") do SET GACOM=%%~a
for %%a in ("Galeco") do SET GALCO=%%~a
for %%a in ("Hikaru") do SET HIKARU=%%~a
for %%a in ("Intellivision") do SET INTEL=%%~a
for %%a in ("Interact Family Computer") do SET INTFC=%%~a
for %%a in ("Atari Jaguar CD") do SET JAGCD=%%~a
for %%a in ("Atari Jaguar") do SET JAG=%%~a
for %%a in ("Jupiter Ace") do set JUPA=%%~a
for %%a in ("Atari Lynx") do SET LYNX=%%~a
for %%a in ("Mega Duck") do SET MDUC=%%~a
for %%a in ("Microtan 65") do SET MITAN=%%~a
for %%a in ("Thomson Mo5") do SET MO5=%%~a
for %%a in ("MS D-O-S") do SET MSDS=%%~a
for %%a in ("Apple Macintosh") do SET MACINT=%%~a
for %%a in ("MTX") do SET MTX=%%~a
for %%a in ("MSX") do SET MSX=%%~a
for %%a in ("MSX2") do SET MSX2=%%~a
for %%a in ("MSXT") do SET MSX TurboR=%%~a
for %%a in ("MZ-700") do SET MZ7=%%~a
for %%a in ("MZ-800") do SET MZ8=%%~a
for %%a in ("Nintendo 64") do SET N64=%%~a
for %%a in ("Naomi") do SET NAOMI=%%~a
for %%a in ("NeoGeo Pocket") do SET NEOPKT=%%~a
for %%a in ("NeoGeo Pocket Color") do SET NEOPKTC=%%~a
for %%a in ("NeoGeo MVS") do SET NEOGE=%%~a
for %%a in ("NeoGeo CD") do SET NEOCD=%%~a
for %%a in ("Nintendo DS") do SET NDS=%%~a
for %%a in ("Nintendo Virtual Boy") do SET NVB=%%~a
for %%a in ("Nintendo GameCube") do SET NGC=%%~a
for %%a in ("Nintendo Game - Watch") do SET GANDW=%%~a
for %%a in ("Nintendo Gameboy") do SET NGB=%%~a
for %%a in ("Nintendo Gameboy Color") do SET NGBC=%%~a
for %%a in ("Nintendo Gameboy Advance") do SET NGBA=%%~a
for %%a in ("Nintendo Entertainment System") do SET NES=%%~a
for %%a in ("Nintendo Famicom") do SET NFAM=%%~a
for %%a in ("Nintendo Satellaview") do SET NSATL=%%~a
for %%a in ("Beats of Rage") do SET OBOR=%%~a
for %%a in ("Tangerine Oric Atmos") do SET ORIC=%%~a
for %%a in ("Odyssey") do SET ODYS=%%~a
for %%a in ("Odyssey 2") do SET ODYS2=%%~a
for %%a in ("Panasonic 3DO") do SET P3DO=%%~a
for %%a in ("NEC PC-6001") do SET PC6K=%%~a
for %%a in ("NEC PC8001") do SET PC81=%%~a
for %%a in ("NEC PC8201") do SET PC82=%%~a
for %%a in ("NEC PC88") do SET PC88=%%~a
for %%a in ("NEC PC88-VA") do SET PC88VA=%%~a
for %%a in ("NEC PC98") do SET PC98=%%~a
for %%a in ("NEC PC9821") do SET PC982=%%~a
for %%a in ("PopCap") do SET PCAP=%%~a
for %%a in ("PC Engine CD") do SET PCECD=%%~a
for %%a in ("PC Engine") do SET PCENG=%%~a
for %%a in ("NEC PC-FX") do SET PCFX=%%~a
for %%a in ("PC Jr") do SET PCJR=%%~a
for %%a in ("Philips P2000") do SET PP2K=%%~a
for %%a in ("Philips VG 5000") do SET PVG5K=%%~a
for %%a in ("Philips Videopac G7400") do SET PVG74=%%~a
for %%a in ("Pocketstation") do SET POCKS=%%~a
for %%a in ("Sony Playstation") do SET PS1=%%~a
for %%a in ("Sony Playstation 2") do SET PS2=%%~a
for %%a in ("Sony Playstation Vita") do SET PSVITA=%%~a
for %%a in ("Sony PS4") do SET PS4=%%~a
for %%a in ("Sony PS3") do SET PS3=%%~a
for %%a in ("Sony PSP") do SET PSP=%%~a
for %%a in ("RCA Studio II") do SET RCAS2=%%~a
for %%a in ("Sam Coupe") do SET SAMC=%%~a
for %%a in ("ScummVM") do SET SCUM=%%~a
for %%a in ("Super Cassette Vision") do SET SCAS=%%~a
for %%a in ("Sega SG-1000") do SET SEG1K=%%~a
for %%a in ("Sega SC-3000") do SET SEG3K=%%~a
for %%a in ("Sega SF-7000") do SET SEGSF=%%~a
for %%a in ("Super Control Station") do SET SEG7K=%%~a
for %%a in ("Sega Genesis") do SET SEGAG=%%~a
for %%a in ("Sega Pico") do SET SEGAP=%%~a
for %%a in ("Sega MegaDrive") do SET SEGAMD=%%~a
for %%a in ("Sega Master System") do SET SEGMS=%%~a
for %%a in ("Sega Dreamcast") do SET SEGDC=%%~a
for %%a in ("Sega Game Gear") do SET SEGG=%%~a
for %%a in ("Sega CD") do SET SEGCD=%%~a
for %%a in ("Sega Model 2") do SET SEGM2=%%~a
for %%a in ("Sega Model 3") do SET SEGM3=%%~a
for %%a in ("Super Famicom") do SET SFAM=%%~a
for %%a in ("Sega 32X") do SET SG32X=%%~a
for %%a in ("SuperGrafx") do SET SGFX=%%~a
for %%a in ("Sega Mega-CD") do SET SEGMCD=%%~a
for %%a in ("Super Nintendo") do SET SNES=%%~a
for %%a in ("Sinclair QL") do SET SNQL=%%~a
for %%a in ("Sord M5") do SET SORD=%%~a
for %%a in ("Spectravideo") do SET SPECV=%%~a
for %%a in ("Sega Saturn") do SET SSAT=%%~a
for %%a in ("Sega STV") do SET SSTV=%%~a
for %%a in ("Sharp X1") do SET SHRPX1=%%~a
for %%a in ("Watara SuperVision") do SET SVIS=%%~a
for %%a in ("Super Gameboy") do set SUPRGB=%%~a
for %%a in ("Taito Type X") do SET TAITX=%%~a
for %%a in ("TurboGrafx 16") do SET TG16=%%~a
for %%a in ("TurboGrafx CD") do SET TGCD=%%~a
for %%a in ("Thomson To7") do SET TO7=%%~a
for %%a in ("Thomson To8") do SET TO8=%%~a
for %%a in ("Tomy Tutor") do SET TOMYT=%%~a
for %%a in ("Touhou") do SET TOUHU=%%~a
for %%a in ("Triforce") do SET TRIF=%%~a
for %%a in ("Vectrex") do SET VECTX=%%~a
for %%a in ("Interon VC 4000") do SET VC4K=%%~a
for %%a in ("Commodore VIC20") do SET VC20=%%~a
for %%a in ("VTech Creativision") do SET VCRV=%%~a
for %%a in ("VTech Laser 200") do SET VLAS2=%%~a
for %%a in ("VTech Laser 310") do SET VLAS3=%%~a
for %%a in ("Xbox 360") do SET X360=%%~a
for %%a in ("X68000") do SET X68K=%%~a
for %%a in ("Xbox") do SET XBX=%%~a
for %%a in ("Nintendo Wii") do SET WII=%%~a
for %%a in ("Nintendo WiiU") do SET WIIU=%%~a
for %%a in ("Windows Games") do SET WIN32=%%~a
for %%a in ("Sinclair ZX Spectrum") do SET ZXSP=%%~a
for %%a in ("Sinclair ZX81") do SET ZX81=%%~a

for %%a in ("Atari800") do SET AT8E=%%~a
for %%a in ("Akiko") do SET AKIKO=%%~a
for %%a in ("Altirra") do SET ALTRA=%%~a
for %%a in ("ArcEm") do SET ARCEM=%%~a
for %%a in ("Arculator") do SET ARLTR=%%~a
for %%a in ("Anex86") do SET ANEX=%%~a
for %%a in ("ArcadePCLoader") do SET APCL=%%~a
for %%a in ("AppleWin") do SET APLWIN=%%~a
for %%a in ("atari++") do SET ATRI=%%~a
for %%a in ("BatchScriptLauncher") do SET BATCHL=%%~a
for %%a in ("BeebEm") do SET BEEBEM=%%~a
for %%a in ("bgb") do set BGB=%%~a
for %%a in ("bsnes") do SET BSNS=%%~a
for %%a in ("BlueMSX") do SET BMSX=%%~a
for %%a in ("Colem") do SET COLEM=%%~a
for %%a in ("Superchip-8") do SET CHIP8=%%~a
for %%a in ("cps3emulator") do SET CPS3EMU=%%~a
for %%a in ("Demul") do SET DMUL=%%~a
for %%a in ("UME") do set UME=%%~a
for %%a in ("DesMume") do SET DESMUME=%%~a
for %%a in ("Dolphin") do SET DOLPH=%%~a
for %%a in ("ElectrEm") do SET ELECEM=%%~a
for %%a in ("em7") do SET EMSEV=%%~a
for %%a in ("ePSXe") do SET EPSXE=%%~a
for %%a in ("FinalBurnAlpha") do SET FBA=%%~a
for %%a in ("Unz") do SET FMUNZ=%%~a
for %%a in ("4DO") do SET FOURDO=%%~a
for %%a in ("FlashPlayer") do SET FSHPL=%%~a
for %%a in ("FreeDO") do SET FRDO=%%~a
for %%a in ("FS-UAE") do SET FSUAE=%%~a
for %%a in ("Fusion") do SET FUSN=%%~a
for %%a in ("fceux") do SET FCEUX=%%~a
for %%a in ("hatari") do SET HATARI=%%~a
for %%a in ("Bliss") do SET INTV=%%~a
for %%a in ("jum52") do SET JUM52=%%~a
for %%a in ("Jagulator") do SET JAGLT=%%~a
for %%a in ("jnes") do SET JNES=%%~a
for %%a in ("jpcsp") do SET JPCSP=%%~a
for %%a in ("jzintv") do SET JZINTV=%%~a
for %%a in ("Kegs32") do SET KEGS=%%~a
for %%a in ("M88") do SET M88=%%~a
for %%a in ("m2emulator") do SET M2EMU=%%~a
for %%a in ("Mednafen") do SET MEDN=%%~a
for %%a in ("MagicEngine") do SET MENG=%%~a
for %%a in ("Mame") do SET MAME=%%~a
for %%a in ("Mess") do SET MESS=%%~a
for %%a in ("DOSBox") do SET MSBOX=%%~a
for %%a in ("mupen64plus") do SET MUPEN=%%~a
for %%a in ("Mugen") do SET MUGN=%%~a
for %%a in ("Nebula") do SET NEBULA=%%~a
for %%a in ("Neko") do SET NEKO=%%~a
for %%a in ("neocd") do SET NEOCDEMU=%%~a
for %%a in ("NeoRaine") do SET NEORAINE=%%~a
for %%a in ("nestopia") do SET NESTP=%%~a
for %%a in ("No$GBA") do SET NOGBA=%%~a
for %%a in ("Nostalgia") do SET NOSTL=%%~a
for %%a in ("NullDC") do SET NULLDC=%%~a
for %%a in ("Ootake") do SET OOTK=%%~a
for %%a in ("OpenMSX") do SET OPNMSX=%%~a
for %%a in ("Pcsx2") do SET PCSX2=%%~a
for %%a in ("pcsxr") do SET PCSXR=%%~a
for %%a in ("Pop Cap") do SET PCAP=%%~a
for %%a in ("Project64") do SET PJ64=%%~a
for %%a in ("ParaJVE") do SET PJVE=%%~a
for %%a in ("3DOplay") do SET PLAY3DO=%%~a
for %%a in ("ProSystem") do SET PROSYS=%%~a
for %%a in ("PPSSPP") do SET PSSP=%%~a
for %%a in ("psx") do SET PSX=%%~a
for %%a in ("ProjectTempest") do SET PTMPS=%%~a
for %%a in ("raine") do SET RAINE=%%~a
for %%a in ("retroArch") do SET RTROA=%%~a
for %%a in ("ScummVM") do SET SCMVM=%%~a
for %%a in ("SimCoupe") do SET SIMC=%%~a
for %%a in ("snes9x") do SET SN9X=%%~a
for %%a in ("SNESGT") do SET SNESGT=%%~a
for %%a in ("Supermodel") do SET SPRM3=%%~a
for %%a in ("SSF") do SET SSF=%%~a
for %%a in ("Steem") do SET STEEM=%%~a
for %%a in ("Stella") do SET STLA=%%~a
for %%a in ("FlashPlayer") do SET SWFPL=%%~a
for %%a in ("TurboEngine") do SET TURBOE=%%~a
for %%a in ("VirtualColeco") do SET VCOLEC=%%~a
for %%a in ("mGBA") do SET MGBA=%%~a
for %%a in ("VisualBoyAdvance") do SET VGBA=%%~a
for %%a in ("WinVICE") do SET VICE=%%~a
for %%a in ("VirtualJaguar") do SET VJAG=%%~a
for %%a in ("VirtuaNes") do SET VNES=%%~a
for %%a in ("EMU7800") do SET VSVH=%%~a
for %%a in ("CD-I") do SET WCDI=%%~a
for %%a in ("WinArcadia") do SET WINARC=%%~a
for %%a in ("WinAPE") do SET WINAPE=%%~a
for %%a in ("WinUAE") do SET WINUAE=%%~a
for %%a in ("WinX68k") do SET WINX68K=%%~a
for %%a in ("XM6") do SET XM6=%%~a
for %%a in ("XM7") do SET XM7=%%~a
for %%a in ("X1turbo") do SET XTURB=%%~a
for %%a in ("Zinc") do SET ZINC=%%~a
for %%a in ("Zsnes") do SET ZSNS=%%~a
for %%a in ("ZXSpin") do SET ZXSPIN=%%~a
