if "%CSTCONS%"=="%P3DO%" set ESRMP=3do
if "%CSTCONS%"=="%CAMIG%" set ESRMP=amiga
if "%CSTCONS%"=="%AMSTR%" set ESRMP=amstradcpc
if "%CSTCONS%"=="%APL2E%" set ESRMP=apple2
if "%CSTCONS%"=="%CPS%" set ESRMP=arcade
if "%CSTCONS%"=="%CPS2%" set ESRMP=arcade
if "%CSTCONS%"=="%GALCO%" set ESRMP=arcade
if "%CSTCONS%"=="%HIKARU%" set ESRMP=arcade
if "%CSTCONS%"=="%ATMS%" set ESRMP=arcade
if "%CSTCONS%"=="%NAOMI%" set ESRMP=arcade
if "%CSTCONS%"=="%TAITX%" set ESRMP=arcade
if "%CSTCONS%"=="%CPS3%" set ESRMP=arcade
if "%CSTCONS%"=="%ARCD%" set ESRMP=arcade
if "%CSTCONS%"=="%AT8H%" set ESRMP=atari800
if "%CSTCONS%"=="%AT26%" set ESRMP=atari2600
if "%CSTCONS%"=="%AT52%" set ESRMP=atari5200
if "%CSTCONS%"=="%AT78%" set ESRMP=atari7800
if "%CSTCONS%"=="%LYNX%" set ESRMP=atarilynx
if "%CSTCONS%"=="%ATST%" set ESRMP=atarist
if "%CSTCONS%"=="%JAG%" set ESRMP=atarijaguar
if "%CSTCONS%"=="%JAGCD%" set ESRMP=atarijaguarcd
if "%CSTCONS%"=="%ATXE%" set ESRMP=atarixe
if "%CSTCONS%"=="%COLEC%" set ESRMP=colecovision
if "%CSTCONS%"=="%CM64%" set ESRMP=c64
if "%CSTCONS%"=="%INTEL%" set ESRMP=intellivision
if "%CSTCONS%"=="%MACIN%" set ESRMP=macintosh
if "%CSTCONS%"=="%XBX%" set ESRMP=xbox
if "%CSTCONS%"=="%X360%" set ESRMP=xbox360
if "%CSTCONS%"=="%NEOCD%" set ESRMP=neogeo
if "%CSTCONS%"=="%NEOGE%" set ESRMP=neogeo
if "%CSTCONS%"=="%NEOPKT%" set ESRMP=ngp
if "%CSTCONS%"=="%NEOPKTC%" set ESRMP=ngpc
if "%CSTCONS%"=="%N3DS%" set ESRMP=n3ds
if "%CSTCONS%"=="%N64%" set ESRMP=n64
if "%CSTCONS%"=="%NDS%" set ESRMP=nds
if "%CSTCONS%"=="%NFAM%" set ESRMP=nes
if "%CSTCONS%"=="%NES%" set ESRMP=nes
if "%CSTCONS%"=="%NGB%" set ESRMP=gb
if "%CSTCONS%"=="%NGBA%" set ESRMP=gba
if "%CSTCONS%"=="%NGBC%" set ESRMP=gbc
if "%CSTCONS%"=="%NGC%" set ESRMP=gc
if "%CSTCONS%"=="%WII%" set ESRMP=wii
if "%CSTCONS%"=="%WIIU%" set ESRMP=wiiu
if "%CSTCONS%"=="%WIN32%" set ESRMP=pc
if "%CSTCONS%"=="%SG32X%" set ESRMP=sega32x
if "%CSTCONS%"=="%SEGCD%" set ESRMP=segacd
if "%CSTCONS%"=="%SEGDC%" set ESRMP=dreamcast
if "%CSTCONS%"=="%SEGG%" set ESRMP=gamegear
if "%CSTCONS%"=="%SEGAG%" set ESRMP=genesis
if "%CSTCONS%"=="%SEGMS%" set ESRMP=mastersystem
if "%CSTCONS%"=="%SEGAMD%" set ESRMP=megadrive
if "%CSTCONS%"=="%SSAT%" set ESRMP=saturn
if "%CSTCONS%"=="%PS1%" set ESRMP=psx
if "%CSTCONS%"=="%PS2%" set ESRMP=ps2
if "%CSTCONS%"=="%PS3%" set ESRMP=ps3
if "%CSTCONS%"=="%PS4%" set ESRMP=ps4
if "%CSTCONS%"=="%PSVITA%" set ESRMP=psvita
if "%CSTCONS%"=="%PSP%" set ESRMP=psp
if "%CSTCONS%"=="%SNES%" set ESRMP=snes
if "%CSTCONS%"=="%SFAM%" set ESRMP=snes
if "%CSTCONS%"=="%PCENG%" set ESRMP=pcengine
if "%CSTCONS%"=="%TGCD%" set ESRMP=pcengine
if "%CSTCONS%"=="%TG16%" set ESRMP=pcengine
if "%CSTCONS%"=="%SGFX%" set ESRMP=pcengine
if "%CSTCONS%"=="%BWS%" set ESRMP=wonderswan
if "%CSTCONS%"=="%BWSC%" set ESRMP=wonderswancolor
if "%CSTCONS%"=="%ZXSP%" set ESRMP=zxspectrum