if not exist "%HPN%\Media\%HYPCON%" mkdir "%HPN%\Media\%HYPCON%"
if not exist "%HPN%\Media\%HYPCON%\Video" mkdir "%HPN%\Media\%HYPCON%\Video"
if not exist "%HPN%\Media\%HYPCON%\Video\Override Tranisitions" mkdir "%HPN%\Media\%HYPCON%\Video\Override Tranisitions"
if not exist "%HPN%\Media\%HYPCON%\Themes" mkdir "%HPN%\Media\%HYPCON%\Themes"
if not exist "%HPN%\Media\%HYPCON%\Sound" mkdir "%HPN%\Media\%HYPCON%\Sound"
if not exist "%HPN%\Media\%HYPCON%\Sound\Background Music" mkdir "%HPN%\Media\%HYPCON%\Sound\Background Music"
if not exist "%HPN%\Media\%HYPCON%\Sound\System Exit" mkdir "%HPN%\Media\%HYPCON%\Sound\System Exit"
if not exist "%HPN%\Media\%HYPCON%\Sound\System Start" mkdir "%HPN%\Media\%HYPCON%\Sound\System Start"
if not exist "%HPN%\Media\%HYPCON%\Sound\Wheel Sounds" mkdir "%HPN%\Media\%HYPCON%\Sound\Wheel Sounds"
if not exist "%HPN%\Media\%HYPCON%\Images" mkdir "%HPN%\Media\%HYPCON%\Images"
if not exist "%HPN%\Media\%HYPCON%\Images\Artwork1" mkdir "%HPN%\Media\%HYPCON%\Images\Artwork1"
if not exist "%HPN%\Media\%HYPCON%\Images\Artwork2" mkdir "%HPN%\Media\%HYPCON%\Images\Artwork2"
if not exist "%HPN%\Media\%HYPCON%\Images\Artwork3" mkdir "%HPN%\Media\%HYPCON%\Images\Artwork3"
if not exist "%HPN%\Media\%HYPCON%\Images\Artwork4" mkdir "%HPN%\Media\%HYPCON%\Images\Artwork4"
if not exist "%HPN%\Media\%HYPCON%\Images\Backgrounds" mkdir "%HPN%\Media\%HYPCON%\Images\Backgrounds"
if not exist "%HPN%\Media\%HYPCON%\Images\Genre" mkdir "%HPN%\Media\%HYPCON%\Images\Genre"
if not exist "%HPN%\Media\%HYPCON%\Images\Genre\Backgrounds" mkdir "%HPN%\Media\%HYPCON%\Images\Genre\Backgrounds"
if not exist "%HPN%\Media\%HYPCON%\Images\Genre\Wheel" mkdir "%HPN%\Media\%HYPCON%\Images\Genre\Wheel"
if not exist "%HPN%\Media\%HYPCON%\Images\Letters" mkdir "%HPN%\Media\%HYPCON%\Images\Letters"
if not exist "%HPN%\Media\%HYPCON%\Images\Other" mkdir "%HPN%\Media\%HYPCON%\Images\Other"
if not exist "%HPN%\Media\%HYPCON%\Images\Particle" mkdir "%HPN%\Media\%HYPCON%\Images\Particle"
if not exist "%HPN%\Media\%HYPCON%\Images\Special" mkdir "%HPN%\Media\%HYPCON%\Images\Special"
if not exist "%HPN%\Media\%HYPCON%\Images\Wheel" mkdir "%HPN%\Media\%HYPCON%\Images\Wheel"
