CALL "%GBC%\dtest.bat"
pushd "%GBC%\net\%MBRWS%"
"%GBC%\fart.exe" "%MBRWS%Xml.config" [BATCHLEXEPTH] "%BATCHL%\%BATCHL%.exe"
"%GBC%\fart.exe" "%MBRWS%Xml.config" [EMUL] "%GBE%\%EMUZ%"
"%GBC%\fart.exe" "%MBRWS%Xml.config" [DAMVAR] "%DAMVAR%"
"%GBC%\fart.exe" "%MBRWS%Xml.config" [DAMVARL] "%DRVLTR%"
"%GBC%\fart.exe" "%MBRWS%Xml.config" [MBINST] "%MBLOC%"
"%GBC%\fart.exe" "%MBRWS%Xml.config" [PRGD] "%PROGRAMDATA%"
"%GBC%\fart.exe" "%MBRWS%Xml.config" [MBRWS] "%MBRWS%"
if exist "%PROGRAMDATA%\%MBRWS%\Plugins\%GBRWS%.dll" "%GBC%\fart.exe" "%MBRWS%Xml.config" "<AllowInternetMetadataProviders>False" "<AllowInternetMetadataProviders>True"
if exist "%PROGRAMDATA%\%MBRWS%\Plugins\%GBRWS%.dll" "%GBC%\fart.exe" "%MBRWS%Xml.config" "<SaveLocalMeta>False" "<SaveLocalMeta>True"
copy /Y "%GBC%\net\%MBRWS%\*.png" "%PROGRAMDATA%\%MBRWS%"
"%GBC%\fart.exe" "Console.vf" [IMG] "%PROGRAMDATA%\%MBRWS%\gFolder.png"
"%GBC%\fart.exe" "Console.vf" [CONS] "%GBG%\%GAM%\%CONS%"
popd
