set CSTCONS=
if /i "%MESMAT%"=="supracan" set CSTCONS=%ACAN%
if /i "%MESMAT%"=="bbcm" set CSTCONS=%ACBBC%
if /i "%MESMAT%"=="a310" set CSTCONS=%ACARC%
if /i "%MESMAT%"=="electron" set CSTCONS=%ACELE%
if /i "%MESMAT%"=="advision" set CSTCONS=%ADVV%
if /i "%MESMAT%"=="gx4000" set CSTCONS=%AMSGX%
if /i "%MESMAT%"=="cpc664" set CSTCONS=%AMSTR%
if /i "%MESMAT%"=="adam" set CSTCONS=%COLADM%
if /i "%MESMAT%"=="cdtv" set CSTCONS=%AMIGTV%
if /i "%MESMAT%"=="cd32" set CSTCONS=%AMIG32%
if /i "%MESMAT%"=="apple2e" set CSTCONS=%APL2E%
if /i "%MESMAT%"=="apple2gs" set CSTCONS=%APL2GS%
if /i "%MESMAT%"=="aquarius" set CSTCONS=%AQURS%
if /i "%MESMAT%"=="apfimag" set CSTCONS=%APFIM%
if /i "%MESMAT%"=="a2600" set CSTCONS=%AT26%
if /i "%MESMAT%"=="a5200" set CSTCONS=%AT52%
if /i "%MESMAT%"=="a7800" set CSTCONS=%AT78%
if /i "%MESMAT%"=="a1200xl" set CSTCONS=%AT8B%
if /i "%MESMAT%"=="a800" set CSTCONS=%AT8H%
if /i "%MESMAT%"=="ste" set CSTCONS=%ATST%
if /i "%MESMAT%"=="xegs" set CSTCONS=%ATXE%
if /i "%MESMAT%"=="astrocde" set CSTCONS=%BALY%
if /i "%MESMAT%"=="wswan" set CSTCONS=%BWS%
if /i "%MESMAT%"=="wscolor" set CSTCONS=%BWSC%
if /i "%MESMAT%"=="a500" set CSTCONS=%CAMIG%
if /i "%MESMAT%"=="cdimono1" set CSTCONS=%CDI%
if /i "%MESMAT%"=="channelf" set CSTCONS=%CHNF%
if /i "%MESMAT%"=="c16" set CSTCONS=%COM16%
if /i "%MESMAT%"=="c64" set CSTCONS=%CM64%
if /i "%MESMAT%"=="c64" set CSTCONS=%CMMAX%
if /i "%MESMAT%"=="pet2001" set CSTCONS=%CMPET%
if /i "%MESMAT%"=="casloopy" set CSTCONS=%CLOOP%
if /i "%MESMAT%"=="pv1000" set CSTCONS=%CAS1K%
if /i "%MESMAT%"=="pv2000" set CSTCONS=%CAS2K%
if /i "%MESMAT%"=="coleco" set CSTCONS=%COLEC%
if /i "%MESMAT%"=="arcadia" set CSTCONS=%EMARC%
if /i "%MESMAT%"=="ep64" set CSTCONS=%ENTP64%
if /i "%MESMAT%"=="ep128" set CSTCONS=%ENTP128%
if /i "%MESMAT%"=="dragon32" set CSTCONS=%DRAG32%
if /i "%MESMAT%"=="fm7" set CSTCONS=%FM7%
if /i "%MESMAT%"=="fmtowns" set CSTCONS=%FMTOWNS%
if /i "%MESMAT%"=="gamecom" set CSTCONS=%GACOM%
if /i "%MESMAT%"=="intv" set CSTCONS=%INTEL%
if /i "%MESMAT%"=="jaguarcd" set CSTCONS=%JAGCD%
if /i "%MESMAT%"=="jaguar" set CSTCONS=%JAG%
if /i "%MESMAT%"=="jupace" set CSTCONS=%JUPA%
if /i "%MESMAT%"=="lynx" set CSTCONS=%LYNX%
if /i "%MESMAT%"=="megaduck" set CSTCONS=%MDUC%
if /i "%MESMAT%"=="microtan" set CSTCONS=%MITAN%
if /i "%MESMAT%"=="mac" set CSTCONS=%MACINT%
if /i "%MESMAT%"=="mtx512" set CSTCONS=%MTX%
if /i "%MESMAT%"=="ax170" set CSTCONS=%MSX%
if /i "%MESMAT%"=="ax370" set CSTCONS=%MSX2%
if /i "%MESMAT%"=="expert3t" set CSTCONS=%MSXTR%
if /i "%MESMAT%"=="mz700" set CSTCONS=%MZ7%
if /i "%MESMAT%"=="mz800" set CSTCONS=%MZ8%
if /i "%MESMAT%"=="n64" set CSTCONS=%N64%
if /i "%MESMAT%"=="ngp" set CSTCONS=%NEOPKT%
if /i "%MESMAT%"=="ngpc" set CSTCONS=%NEOPKTC%
if /i "%MESMAT%"=="aes" set CSTCONS=%NEOGE%
if /i "%MESMAT%"=="neocd" set CSTCONS=%NEOCD%
if /i "%MESMAT%"=="vboy" set CSTCONS=%NVB%
if /i "%MESMAT%"=="gameboy" set CSTCONS=%NGB%
if /i "%MESMAT%"=="gbcolor" set CSTCONS=%NGBC%
if /i "%MESMAT%"=="gba" set CSTCONS=%NGBA%
if /i "%MESMAT%"=="nes" set CSTCONS=%NES%
if /i "%MESMAT%"=="famicom" set CSTCONS=%NFAM%
if /i "%MESMAT%"=="snes" set CSTCONS=%NSATL%
if /i "%MESMAT%"=="odyssey2" set CSTCONS=%ODYS2%
if /i "%MESMAT%"=="odyssey3" set CSTCONS=%ODYS3%
if /i "%MESMAT%"=="3do_m2" set CSTCONS=%P3DO%
if /i "%MESMAT%"=="pc6001" set CSTCONS=%PC6K%
if /i "%MESMAT%"=="pc8801" set CSTCONS=%PC88%
if /i "%MESMAT%"=="pc88va" set CSTCONS=%PC88VA%
if /i "%MESMAT%"=="pc9821xs" set CSTCONS=%PC98%
if /i "%MESMAT%"=="pce" set CSTCONS=%PCECD%
if /i "%MESMAT%"=="pce" set CSTCONS=%PCENG%
if /i "%MESMAT%"=="pcfx" set CSTCONS=%PCFX%
if /i "%MESMAT%"=="drpcjr" set CSTCONS=%PCJR%
if /i "%MESMAT%"=="pc2000" set CSTCONS=%PPC2K%
if /i "%MESMAT%"=="vg5k" set CSTCONS=%PVG5K%
if /i "%MESMAT%"=="videopac" set CSTCONS=%PVG74%
if /i "%MESMAT%"=="pockstat" set CSTCONS=%POCKS%
if /i "%MESMAT%"=="psu" set CSTCONS=%PS1%
if /i "%MESMAT%"=="oric1" set CSTCONS=%ORIC%
if /i "%MESMAT%"=="studio2" set CSTCONS=%RCAS2%
if /i "%MESMAT%"=="samcoupe" set CSTCONS=%SAMC%
if /i "%MESMAT%"=="scv" set CSTCONS=%SCAS%
if /i "%MESMAT%"=="sg1000" set CSTCONS=%SEG1K%
if /i "%MESMAT%"=="sc3000" set CSTCONS=%SEG3K%
if /i "%MESMAT%"=="sf7000" set CSTCONS=%SEGSF%
if /i "%MESMAT%"=="sf7000" set CSTCONS=%SEG7K%
if /i "%MESMAT%"=="genesis" set CSTCONS=%SEGAG%
if /i "%MESMAT%"=="pico" set CSTCONS=%SEGAP%
if /i "%MESMAT%"=="megadriv" set CSTCONS=%SEGAMD%
if /i "%MESMAT%"=="sms" set CSTCONS=%SEGMS%
if /i "%MESMAT%"=="tutor" set CSTCONS=%TOMYT%
if /i "%MESMAT%"=="mo5" set CSTCONS=%MO5%
if /i "%MESMAT%"=="t07" set CSTCONS=%TO7%
if /i "%MESMAT%"=="to8" set CSTCONS=%TO8%
if /i "%MESMAT%"=="exl100" set CSTCONS=%EXL1H%
if /i "%MESMAT%"=="interact" set CSTCONS=%INTFC%
if /i "%MESMAT%"=="lynx128k" set CSTCONS=%CMPLNX%
if /i "%MESMAT%"=="gamegear" set CSTCONS=%SEGG%
if /i "%MESMAT%"=="segacd" set CSTCONS=%SEGCD%
if /i "%MESMAT%"=="snes" set CSTCONS=%SFAM%
if /i "%MESMAT%"=="32x" set CSTCONS=%SG32X%
if /i "%MESMAT%"=="sgx" set CSTCONS=%SGFX%
if /i "%MESMAT%"=="megacd" set CSTCONS=%SEGMCD%
if /i "%MESMAT%"=="snes" set CSTCONS=%SNES%
if /i "%MESMAT%"=="ql" set CSTCONS=%SNQL%
if /i "%MESMAT%"=="m5p" set CSTCONS=%SORD%
if /i "%MESMAT%"=="sv318" set CSTCONS=%SPECV%
if /i "%MESMAT%"=="vsaturn" set CSTCONS=%SSAT%
if /i "%MESMAT%"=="x1" set CSTCONS=%SHRPX1%
if /i "%MESMAT%"=="svision" set CSTCONS=%SVIS%
if /i "%MESMAT%"=="supergb" set CSTCONS=%SUPRGB%
if /i "%MESMAT%"=="tg16" set CSTCONS=%TG16%
if /i "%MESMAT%"=="tg16" set CSTCONS=%TGCD%
if /i "%MESMAT%"=="vectrex" set CSTCONS=%VECTX%
if /i "%MESMAT%"=="vc4000" set CSTCONS=%VC4K%
if /i "%MESMAT%"=="vic20" set CSTCONS=%VC20%
if /i "%MESMAT%"=="crvision" set CSTCONS=%VCRV%
if /i "%MESMAT%"=="laser200" set CSTCONS=%VLAS2%
if /i "%MESMAT%"=="laser310" set CSTCONS=%VLAS3%
if /i "%MESMAT%"=="x68000" set CSTCONS=%X68K%
if /i "%MESMAT%"=="spectrum" set CSTCONS=%ZXSP%
if /i "%MESMAT%"=="zx81" set CSTCONS=%ZX81%
