if /I "%ARCE%"==".ws" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%BWS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".wsc" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%BWSC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".x64" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".t64" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".g64" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".d64" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".prg" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%CM64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".xex" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AT8H%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".atr" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AT8H%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".obx" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AT8H%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pro" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AT8H%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".ngc" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NEOPKTC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".neo" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NEOPKTC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".ngp" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NEOPKT%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".npk" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NEOPKT%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".int" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%INTEL%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".col" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%COLEC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".a78" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AT78%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".a26" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AT26%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".a52" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AT52%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".st" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%ATST%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".msa" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%ATST%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".lnx" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%LYNX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".v64" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%N64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".z64" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%N64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".n64" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%N64%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".srl" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NDS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nds" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NDS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nd5" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NDS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gb" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NGB%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gbc" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NGBC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".swf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%FLASH%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".jso" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%PSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".prx" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%PSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".ciso" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%PSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".cso" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%PSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".jag" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%JAG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".elf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%WII%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".ciso" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%WII%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".dol" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%WII%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".wad" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%WII%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".wbfs" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%WII%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sgb" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NGBA%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gba" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NGBA%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".vb" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NVB%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".vboy" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NVB%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".mx2" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%MSX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".mx1" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%MSX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".unf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nsf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nes" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".smc" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SNES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pco" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SEGAP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gen" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SEGAG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".tzx" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%ZXSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sna" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%ZXSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".z80" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%ZXSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sg" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SEG1K%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sms" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SEGMS%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gg" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SEGG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".32x" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SG32X%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pbp" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%PSP%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sgx" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SGFX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sad" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".mgt" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sdf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sbt" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".td0" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".cbm" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SAMC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pce" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%TG16%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".d77" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%FM7%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".t77" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%FM7%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".vfd" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%FM7%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".dim" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%X68K%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gcz" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NGC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".gcm" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NGC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".vec" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%VECTX%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".pgm" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAMs%\%CONS%\%EMARC%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".fds" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NFAM%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".sfc" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SFAM%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".nez" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NES%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".md" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SEGAG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".smd" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%SEGAG%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".ngc" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%NEOPKT%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".rp2" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AMSTR%" "%ARCN%" && SET FNDEXT=1
if /I "%ARCE%"==".dsk" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%GAM%\%CONS%\%AMSTR%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".ccd" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".cdz" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".cdi" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".iso" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".img" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".nrg" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".mdf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".mds" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".cue" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".bin" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".adf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".rom" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".do" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".po" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".2mg" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".cas" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".xdf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".ipf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".dsk" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".tap" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".wav" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".hdf" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".dup" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".d88" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".2hd" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".2dd" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".fdi" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".dsd" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if /i "%ARCE%"==".ssd" "%UNRAR%" e -y -o+ "%RARN%" "%GBG%\%ROMJ%" "%ARCN%" && SET FNDEXT=1
if "%FNDEXT%"=="1" move /Y "%RARN%" "%GBG%\%ROMJ%\SORTED ARCHIVES"
if "%FNDEXT%"=="1" set /a INARCH+=1
if "%FNDEXT%"=="1" %BSTRT% "%WBUSY%" "RJ_GUI" "FOUND %INARCH% ROMS in archives." /marquee