SET MTYP=
if /I "%ARCE%"==".mx1" SET MTYP=[TYP]
if /i "%ARCE%"==".bin" SET MTYP=[TYP]
if /i "%ARCE%"==".rom" SET MTYP=[TYP]
if /I "%ARCE%"==".ws" SET MTYP=cart
if /I "%ARCE%"==".sv" SET MTYP=cart
if /I "%ARCE%"==".wsc" SET MTYP=cart
if /I "%ARCE%"==".x64" SET MTYP=cart
if /I "%ARCE%"==".p00" SET MTYP=quik
if /I "%ARCE%"==".t64" SET MTYP=quik
if /I "%ARCE%"==".g64" SET MTYP=flop
if /I "%ARCE%"==".d64" SET MTYP=flop
if /I "%ARCE%"==".xex" SET MTYP=flop
if /I "%ARCE%"==".1dd" SET MTYP=flop1
if /I "%ARCE%"==".atr" SET MTYP=flop1
if /I "%ARCE%"==".obx" SET MTYP=flop1
if /I "%ARCE%"==".pro" SET MTYP=flop
if /I "%ARCE%"==".ngc" SET MTYP=cart
if /I "%ARCE%"==".emr" SET MTYP=cart
if /I "%ARCE%"==".neo" SET MTYP=cart
if /I "%ARCE%"==".ngp" SET MTYP=cart
if /I "%ARCE%"==".gme" SET MTYP=cart
if /I "%ARCE%"==".npk" SET MTYP=cart
if /I "%ARCE%"==".int" SET MTYP=cart
if /I "%ARCE%"==".col" SET MTYP=cart
if /I "%ARCE%"==".a78" SET MTYP=cart
if /I "%ARCE%"==".a26" SET MTYP=cart
if /I "%ARCE%"==".a52" SET MTYP=cart
if /I "%ARCE%"==".mfi" SET MTYP=flop
if /I "%ARCE%"==".dfi" SET MTYP=flop
if /I "%ARCE%"==".stx" SET MTYP=flop
if /I "%ARCE%"==".st" SET MTYP=flop
if /I "%ARCE%"==".msa" SET MTYP=flop
if /I "%ARCE%"==".lnx" SET MTYP=cart
if /I "%ARCE%"==".v64" SET MTYP=cart
if /I "%ARCE%"==".gb" SET MTYP=cart
if /I "%ARCE%"==".z64" SET MTYP=cart
if /I "%ARCE%"==".n64" SET MTYP=cart
if /I "%ARCE%"==".gbc" SET MTYP=cart
if /I "%ARCE%"==".jag" SET MTYP=cart
if /I "%ARCE%"==".sgb" SET MTYP=cart
if /I "%ARCE%"==".gba" SET MTYP=cart
if /I "%ARCE%"==".vb" SET MTYP=cart
if /I "%ARCE%"==".vboy" SET MTYP=cart
if /I "%ARCE%"==".mx2" SET MTYP=flop
if /I "%ARCE%"==".unf" SET MTYP=cart
if /I "%ARCE%"==".nsf" SET MTYP=cart
if /I "%ARCE%"==".nsf" SET MTYP=cart
if /I "%ARCE%"==".nes" SET MTYP=cart
if /I "%ARCE%"==".smc" SET MTYP=cart
if /I "%ARCE%"==".pco" SET MTYP=cart
if /I "%ARCE%"==".gen" SET MTYP=cart
if /I "%ARCE%"==".tzx" SET MTYP=cass
if /I "%ARCE%"==".sna" SET MTYP=dump
if /I "%ARCE%"==".z80" SET MTYP=dump
if /I "%ARCE%"==".sav" SET MTYP=dump
if /I "%ARCE%"==".ach" SET MTYP=dump
if /I "%ARCE%"==".ace" SET MTYP=dump
if /I "%ARCE%"==".frz" SET MTYP=dump
if /I "%ARCE%"==".sem" SET MTYP=dump
if /I "%ARCE%"==".snx" SET MTYP=dump
if /I "%ARCE%"==".zx" SET MTYP=dump
if /I "%ARCE%"==".sg" SET MTYP=cart
if /I "%ARCE%"==".sms" SET MTYP=cart
if /I "%ARCE%"==".gg" SET MTYP=cart
if /I "%ARCE%"==".32x" SET MTYP=cart
if /I "%ARCE%"==".sgx" SET MTYP=cart
if /I "%ARCE%"==".sad" SET MTYP=flop
if /I "%ARCE%"==".mgt" SET MTYP=flop1
if /I "%ARCE%"==".td0" SET MTYP=flop1
if /I "%ARCE%"==".opk" SET MTYP=cart
if /I "%ARCE%"==".pce" SET MTYP=cart
if /I "%ARCE%"==".d77" SET MTYP=flop1
if /I "%ARCE%"==".blk" SET MTYP=cass
if /I "%ARCE%"==".bit" SET MTYP=cass
if /I "%ARCE%"==".t77" SET MTYP=cass
if /I "%ARCE%"==".uef" SET MTYP=cass
if /I "%ARCE%"==".wav" SET MTYP=cass
if /I "%ARCE%"==".mdv" SET MTYP=cass
if /I "%ARCE%"==".rk" SET MTYP=cass
if /I "%ARCE%"==".rkr" SET MTYP=cass
if /I "%ARCE%"==".rk8" SET MTYP=cass
if /I "%ARCE%"==".gam" SET MTYP=cass
if /I "%ARCE%"==".g16" SET MTYP=cass
if /I "%ARCE%"==".pki" SET MTYP=cass
if /I "%ARCE%"==".mtx" SET MTYP=dump
if /I "%ARCE%"==".dim" SET MTYP=flop1
if /I "%ARCE%"==".swc" SET MTYP=cart
if /I "%ARCE%"==".fig" SET MTYP=cart
if /I "%ARCE%"==".vec" SET MTYP=cart
if /I "%ARCE%"==".cmd" SET MTYP=quik
if /I "%ARCE%"==".scr" SET MTYP=quik
if /I "%ARCE%"==".prg" SET MTYP=quik
if /I "%ARCE%"==".pgm" SET MTYP=quik
if /I "%ARCE%"==".tvc" SET MTYP=quik
if /I "%ARCE%"==".fds" SET MTYP=flop
if /I "%ARCE%"==".sfc" SET MTYP=cart
if /I "%ARCE%"==".nez" SET MTYP=cart
if /I "%ARCE%"==".md" SET MTYP=cart
if /I "%ARCE%"==".m7" SET MTYP=cart
if /I "%ARCE%"==".smd" SET MTYP=cart
if /I "%ARCE%"==".adf" SET MTYP=flop
if /I "%ARCE%"==".rp2" SET MTYP=cart
if /I "%ARCE%"==".sap" SET MTYP=flop1
if /I "%ARCE%"==".qd" SET MTYP=flop1
if /I "%ARCE%"==".os9" SET MTYP=flop1
if /I "%ARCE%"==".dsk" SET MTYP=flop1
if /i "%ARCE%"==".zmk" SET MTYP=flop1
if /i "%ARCE%"==".img" SET MTYP=flop1
if /i "%ARCE%"==".20" SET MTYP=cart
if /i "%ARCE%"==".40" SET MTYP=cart
if /i "%ARCE%"==".60" SET MTYP=cart
if /i "%ARCE%"==".70" SET MTYP=cart
if /i "%ARCE%"==".b0" SET MTYP=cart
if /i "%ARCE%"==".a0" SET MTYP=cart
if /i "%ARCE%"==".cpr" SET MTYP=cart
if /i "%ARCE%"==".crt" SET MTYP=cart
if /i "%ARCE%"==".do" SET MTYP=flop1
if /i "%ARCE%"==".po" SET MTYP=flop1
if /i "%ARCE%"==".2mg" SET MTYP=flop3
if /i "%ARCE%"==".cas" SET MTYP=cass
if /i "%ARCE%"==".xdf" SET MTYP=flop1
if /i "%ARCE%"==".ipf" SET MTYP=flop
if /i "%ARCE%"==".tap" SET MTYP=cass
if /i "%ARCE%"==".wav" SET MTYP=cass
if /i "%ARCE%"==".k7" SET MTYP=cass
if /i "%ARCE%"==".cin" SET MTYP=cass
if /i "%ARCE%"==".for" SET MTYP=cass
if /i "%ARCE%"==".hdf" SET MTYP=sasi
if /i "%ARCE%"==".dup" SET MTYP=cart
if /i "%ARCE%"==".ima" SET MTYP=flop1
if /i "%ARCE%"==".imd" SET MTYP=flop1
if /i "%ARCE%"==".cqm" SET MTYP=flop1
if /i "%ARCE%"==".d88" SET MTYP=flop1
if /i "%ARCE%"==".2hd" SET MTYP=flop1
if /i "%ARCE%"==".2dd" SET MTYP=flop1
if /i "%ARCE%"==".fdi" SET MTYP=flop1
if /i "%ARCE%"==".dsd" SET MTYP=cart
if /i "%ARCE%"==".hd" SET MTYP=hard1
if "%OUTZIP%"=="1" exit /b
:writebat
pushd "%CUSTCONSPTH%\%CSTROM%"
if "%MTYP%" NEQ "" "%GBC%\fart.exe" "*.bat" [TYP] %MTYP%