set MESMAT=
if /i "%CSTCONS%"=="%ACAN%" set MESMAT=supracan
if /i "%CSTCONS%"=="%ACBBC%" set MESMAT=bbcm
if /i "%CSTCONS%"=="%ACARC%" set MESMAT=a310
if /i "%CSTCONS%"=="%ACELE%" set MESMAT=electron
if /i "%CSTCONS%"=="%ADVV%" set MESMAT=advision
if /i "%CSTCONS%"=="%AMSGX%" set MESMAT=gx4000
if /i "%CSTCONS%"=="%AMSTR%" set MESMAT=cpc664
if /i "%CSTCONS%"=="%COLADM%" set MESMAT=adam
if /i "%CSTCONS%"=="%AMIGTV%" set MESMAT=cdtv
if /i "%CSTCONS%"=="%AMIG32%" set MESMAT=cd32
if /i "%CSTCONS%"=="%APL2E%" set MESMAT=apple2e
if /i "%CSTCONS%"=="%APL2GS%" set MESMAT=apple2gs
if /i "%CSTCONS%"=="%AQURS%" set MESMAT=aquarius
if /i "%CSTCONS%"=="%APFIM%" set MESMAT=apfimag
if /i "%CSTCONS%"=="%AT26%" set MESMAT=a2600
if /i "%CSTCONS%"=="%AT52%" set MESMAT=a5200
if /i "%CSTCONS%"=="%AT78%" set MESMAT=a7800
if /i "%CSTCONS%"=="%AT8B%" set MESMAT=a1200xl
if /i "%CSTCONS%"=="%AT8H%" set MESMAT=a800
if /i "%CSTCONS%"=="%ATST%" set MESMAT=ste
if /i "%CSTCONS%"=="%ATXE%" set MESMAT=xegs
if /i "%CSTCONS%"=="%BALY%" set MESMAT=astrocde
if /i "%CSTCONS%"=="%BWS%" set MESMAT=wswan
if /i "%CSTCONS%"=="%BWSC%" set MESMAT=wscolor
if /i "%CSTCONS%"=="%CAMIG%" set MESMAT=a500
if /i "%CSTCONS%"=="%CDI%" set MESMAT=cdimono1
if /i "%CSTCONS%"=="%CHNF%" set MESMAT=channelf
if /i "%CSTCONS%"=="%COM16%" set MESMAT=c16
if /i "%CSTCONS%"=="%CM64%" set MESMAT=c64
if /i "%CSTCONS%"=="%CMMAX%" set MESMAT=c64
if /i "%CSTCONS%"=="%CMPET%" set MESMAT=pet2001
if /i "%CSTCONS%"=="%CLOOP%" set MESMAT=casloopy
if /i "%CSTCONS%"=="%CAS1K%" set MESMAT=pv1000
if /i "%CSTCONS%"=="%CAS2K%" set MESMAT=pv2000
if /i "%CSTCONS%"=="%COLEC%" set MESMAT=coleco
if /i "%CSTCONS%"=="%EMARC%" set MESMAT=arcadia
if /i "%CSTCONS%"=="%ENTP64%" set MESMAT=ep64
if /i "%CSTCONS%"=="%ENTP128%" set MESMAT=ep128
if /i "%CSTCONS%"=="%DRAG32%" set MESMAT=dragon32
if /i "%CSTCONS%"=="%FM7%" set MESMAT=fm7
if /i "%CSTCONS%"=="%FMTOWNS%" set MESMAT=fmtowns
if /i "%CSTCONS%"=="%GACOM%" set MESMAT=gamecom
if /i "%CSTCONS%"=="%INTEL%" set MESMAT=intv
if /i "%CSTCONS%"=="%JAGCD%" set MESMAT=jaguarcd
if /i "%CSTCONS%"=="%JAG%" set MESMAT=jaguar
if /i "%CSTCONS%"=="%JUPA%" set MESMAT=jupace
if /i "%CSTCONS%"=="%LYNX%" set MESMAT=lynx
if /i "%CSTCONS%"=="%MDUC%" set MESMAT=megaduck
if /i "%CSTCONS%"=="%MITAN%" set MESMAT=microtan
if /i "%CSTCONS%"=="%MACINT%" set MESMAT=mac
if /i "%CSTCONS%"=="%MTX%" set MESMAT=mtx512
if /i "%CSTCONS%"=="%MSX%" set MESMAT=ax170
if /i "%CSTCONS%"=="%MSX2%" set MESMAT=ax370
if /i "%CSTCONS%"=="%MSXTR%" set MESMAT=expert3t
if /i "%CSTCONS%"=="%MZ7%" set MESMAT=mz700
if /i "%CSTCONS%"=="%MZ8%" set MESMAT=mz800
if /i "%CSTCONS%"=="%N64%" set MESMAT=n64
if /i "%CSTCONS%"=="%NEOPKT%" set MESMAT=ngp
if /i "%CSTCONS%"=="%NEOPKTC%" set MESMAT=ngpc
if /i "%CSTCONS%"=="%NEOGE%" set MESMAT=aes
if /i "%CSTCONS%"=="%NEOCD%" set MESMAT=neocd
if /i "%CSTCONS%"=="%NVB%" set MESMAT=vboy
if /i "%CSTCONS%"=="%NGB%" set MESMAT=gameboy
if /i "%CSTCONS%"=="%NGBC%" set MESMAT=gbcolor
if /i "%CSTCONS%"=="%NGBA%" set MESMAT=gba
if /i "%CSTCONS%"=="%NES%" set MESMAT=nes
if /i "%CSTCONS%"=="%NFAM%" set MESMAT=famicom
if /i "%CSTCONS%"=="%NSATL%" set MESMAT=snes
if /i "%CSTCONS%"=="%ODYS2%" set MESMAT=odyssey2
if /i "%CSTCONS%"=="%ODYS3%" set MESMAT=odyssey3
if /i "%CSTCONS%"=="%P3DO%" set MESMAT=3do
if /i "%CSTCONS%"=="%PC6K%" set MESMAT=pc6001
if /i "%CSTCONS%"=="%PC88%" set MESMAT=pc8801
if /i "%CSTCONS%"=="%PC88VA%" set MESMAT=pc88va
if /i "%CSTCONS%"=="%PC98%" set MESMAT=pc9821xs
if /i "%CSTCONS%"=="%PCECD%" set MESMAT=pce
if /i "%CSTCONS%"=="%PCENG%" set MESMAT=pce
if /i "%CSTCONS%"=="%PCFX%" set MESMAT=pcfx
if /i "%CSTCONS%"=="%PCJR%" set MESMAT=drpcjr
if /i "%CSTCONS%"=="%PPC2K%" set MESMAT=pc2000
if /i "%CSTCONS%"=="%PVG5K%" set MESMAT=vg5k
if /i "%CSTCONS%"=="%PVG74%" set MESMAT=videopac
if /i "%CSTCONS%"=="%POCKS%" set MESMAT=pockstat
if /i "%CSTCONS%"=="%PS1%" set MESMAT=psu
if /i "%CSTCONS%"=="%ORIC%" set MESMAT=oric1
if /i "%CSTCONS%"=="%RCAS2%" set MESMAT=studio2
if /i "%CSTCONS%"=="%SAMC%" set MESMAT=samcoupe
if /i "%CSTCONS%"=="%SCAS%" set MESMAT=scv
if /i "%CSTCONS%"=="%SEG1K%" set MESMAT=sg1000
if /i "%CSTCONS%"=="%SEG3K%" set MESMAT=sc3000
if /i "%CSTCONS%"=="%SEGSF%" set MESMAT=sf7000
if /i "%CSTCONS%"=="%SEG7K%" set MESMAT=sf7000
if /i "%CSTCONS%"=="%SEGAG%" set MESMAT=genesis
if /i "%CSTCONS%"=="%SEGAP%" set MESMAT=pico
if /i "%CSTCONS%"=="%SEGAMD%" set MESMAT=megadriv
if /i "%CSTCONS%"=="%SEGMS%" set MESMAT=sms
if /i "%CSTCONS%"=="%TOMYT%" set MESMAT=tutor
if /i "%CSTCONS%"=="%MO5%" set MESMAT=mo5
if /i "%CSTCONS%"=="%TO7%" set MESMAT=t07
if /i "%CSTCONS%"=="%TO8%" set MESMAT=to8
if /i "%CSTCONS%"=="%EXL1H%" set MESMAT=exl100
if /i "%CSTCONS%"=="%INTFC%" set MESMAT=interact
if /i "%CSTCONS%"=="%CMPLNX%" set MESMAT=lynx128k
if /i "%CSTCONS%"=="%SEGG%" set MESMAT=gamegear
if /i "%CSTCONS%"=="%SEGCD%" set MESMAT=segacd
if /i "%CSTCONS%"=="%SFAM%" set MESMAT=snes
if /i "%CSTCONS%"=="%SG32X%" set MESMAT=32x
if /i "%CSTCONS%"=="%SGFX%" set MESMAT=sgx
if /i "%CSTCONS%"=="%SEGMCD%" set MESMAT=megacd
if /i "%CSTCONS%"=="%SNES%" set MESMAT=snes
if /i "%CSTCONS%"=="%SNQL%" set MESMAT=ql
if /i "%CSTCONS%"=="%SORD%" set MESMAT=m5p
if /i "%CSTCONS%"=="%SPECV%" set MESMAT=sv318
if /i "%CSTCONS%"=="%SSAT%" set MESMAT=vsaturn
if /i "%CSTCONS%"=="%SHRPX1%" set MESMAT=x1
if /i "%CSTCONS%"=="%SVIS%" set MESMAT=svision
if /i "%CSTCONS%"=="%SUPRGB%" set MESMAT=supergb
if /i "%CSTCONS%"=="%TG16%" set MESMAT=tg16
if /i "%CSTCONS%"=="%TGCD%" set MESMAT=tg16
if /i "%CSTCONS%"=="%VECTX%" set MESMAT=vectrex
if /i "%CSTCONS%"=="%VC4K%" set MESMAT=vc4000
if /i "%CSTCONS%"=="%VC20%" set MESMAT=vic20
if /i "%CSTCONS%"=="%VCRV%" set MESMAT=crvision
if /i "%CSTCONS%"=="%VLAS2%" set MESMAT=laser200
if /i "%CSTCONS%"=="%VLAS3%" set MESMAT=laser310
if /i "%CSTCONS%"=="%X68K%" set MESMAT=x68000
if /i "%CSTCONS%"=="%ZXSP%" set MESMAT=spectrum
if /i "%CSTCONS%"=="%ZX81%" set MESMAT=zx81
