echo ---------->"%GBC%\inbet.ini"
echo Nintendo Gamecube=>>"%GBC%\inbet.ini"
echo Sony PSP=>>"%GBC%\inbet.ini"
echo ----------=>>"%GBC%\inbet.ini"
echo Daphne=>>"%GBC%\inbet.ini"
echo Nintendo Wii=>>"%GBC%\inbet.ini"
echo Sony Playstation 2=>>"%GBC%\inbet.ini"
echo ----------=>>"%GBC%\inbet.ini"
echo Commodore Amiga CD32=>>"%GBC%\inbet.ini"
echo Atari Jaguar CD=>>"%GBC%\inbet.ini"
echo FM Towns=>>"%GBC%\inbet.ini"
echo NeoGeo CD=>>"%GBC%\inbet.ini"
echo Panasonic 3DO=>>"%GBC%\inbet.ini"
echo Philips CD-I=>>"%GBC%\inbet.ini"
echo Sega CD=>>"%GBC%\inbet.ini"
echo Sega Saturn=>>"%GBC%\inbet.ini"
echo Sega Dreamcast=>>"%GBC%\inbet.ini"
echo Sony Playstation=>>"%GBC%\inbet.ini"
echo PC Engine CD=>>"%GBC%\inbet.ini"
echo TurboGrafx CD=>>"%GBC%\inbet.ini"
echo ----------=>>"%GBC%\inbet.ini"
echo -New Console-=>>"%GBC%\inbet.ini"
echo ----------=>>"%GBC%\inbet.ini"

echo ---------->"%GBC%\cdimg.ini"
echo Commodore Amiga CD32=>>"%GBC%\cdimg.ini"
echo Atari Jaguar CD=>>"%GBC%\cdimg.ini"
echo FM Towns=>>"%GBC%\cdimg.ini"
echo NeoGeo CD=>>"%GBC%\cdimg.ini"
echo Panasonic 3DO=>>"%GBC%\cdimg.ini"
echo Philips CD-I=>>"%GBC%\cdimg.ini"
echo Sega CD=>>"%GBC%\cdimg.ini"
echo Sega Saturn=>>"%GBC%\cdimg.ini"
echo Sega Dreamcast=>>"%GBC%\cdimg.ini"
echo Sony Playstation=>>"%GBC%\cdimg.ini"
echo PC Engine CD=>>"%GBC%\cdimg.ini"
echo TurboGrafx CD=>>"%GBC%\cdimg.ini"
echo ----------=>>"%GBC%\cdimg.ini"
echo Nintendo Gamecube=>>"%GBC%\cdimg.ini"
echo Sony PSP=>>"%GBC%\cdimg.ini"
echo Daphne=>>"%GBC%\cdimg.ini"
echo Nintendo Wii=>>"%GBC%\cdimg.ini"
echo Sony Playstation 2=>>"%GBC%\cdimg.ini"
echo ----------=>>"%GBC%\cdimg.ini"
echo -New Console-=>>"%GBC%\cdimg.ini"
echo ----------=>>"%GBC%\cdimg.ini"

echo ---------->"%GBC%\dvdimg.ini"
echo Daphne=>>"%GBC%\dvdimg.ini"
echo Nintendo Wii=>>"%GBC%\dvdimg.ini"
echo Sony Playstation 2=>>"%GBC%\dvdimg.ini"

echo ----------=>>"%GBC%\dvdimg.ini"
echo Commodore Amiga CD32=>>"%GBC%\dvdimg.ini"
echo Atari Jaguar CD=>>"%GBC%\dvdimg.ini"
echo FM Towns=>>"%GBC%\dvdimg.ini"
echo NeoGeo CD=>>"%GBC%\dvdimg.ini"
echo Panasonic 3DO=>>"%GBC%\dvdimg.ini"
echo Philips CD-I=>>"%GBC%\dvdimg.ini"
echo Sega CD=>>"%GBC%\dvdimg.ini"
echo Sega Saturn=>>"%GBC%\dvdimg.ini"
echo Sega Dreamcast=>>"%GBC%\dvdimg.ini"
echo Sony Playstation=>>"%GBC%\dvdimg.ini"
echo PC Engine CD=>>"%GBC%\dvdimg.ini"
echo TurboGrafx CD=>>"%GBC%\dvdimg.ini"
echo Nintendo Gamecube=>>"%GBC%\dvdimg.ini"
echo Sony PSP=>>"%GBC%\dvdimg.ini"

echo ----------=>>"%GBC%\dvdimg.ini"
echo -New Console-=>>"%GBC%\dvdimg.ini"
echo ----------=>>"%GBC%\dvdimg.ini"

echo ---------->"%GBC%\discimg.ini"
echo Commodore Amiga CD32=>>"%GBC%\discimg.ini"
echo Atari Jaguar CD=>>"%GBC%\discimg.ini"
echo FM Towns=>>"%GBC%\discimg.ini"
echo NeoGeo CD=>>"%GBC%\discimg.ini"
echo Panasonic 3DO=>>"%GBC%\discimg.ini"
echo Philips CD-I=>>"%GBC%\discimg.ini"
echo Sega CD=>>"%GBC%\discimg.ini"
echo Sega Saturn=>>"%GBC%\discimg.ini"
echo Sega Dreamcast=>>"%GBC%\discimg.ini"
echo Sony Playstation=>>"%GBC%\discimg.ini"
echo PC Engine CD=>>"%GBC%\discimg.ini"
echo TurboGrafx CD=>>"%GBC%\discimg.ini"
echo Nintendo Wii=>>"%GBC%\discimg.ini"
echo Sony Playstation 2=>>"%GBC%\discimg.ini"
echo Nintendo Gamecube=>>"%GBC%\discimg.ini"
echo Sony PSP=>>"%GBC%\discimg.ini"
echo ----------=>>"%GBC%\discimg.ini"
echo -New Console-=>>"%GBC%\discimg.ini"
echo ----------=>>"%GBC%\discimg.ini"

echo ---------->"%GBC%\binimg.ini"
echo Commodore Amiga CD32=>>"%GBC%\binimg.ini"
echo Atari Jaguar CD=>>"%GBC%\binimg.ini"
echo FM Towns=>>"%GBC%\binimg.ini"
echo Nintendo Wii=>>"%GBC%\binimg.ini"
echo NeoGeo CD=>>"%GBC%\binimg.ini"
echo Panasonic 3DO=>>"%GBC%\binimg.ini"
echo Philips CD-I=>>"%GBC%\binimg.ini"
echo Daphne=>>"%GBC%\binimg.ini"
echo Sega CD=>>"%GBC%\binimg.ini"
echo Sega Saturn=>>"%GBC%\binimg.ini"
echo Sega Dreamcast=>>"%GBC%\binimg.ini"
echo Sony Playstation=>>"%GBC%\binimg.ini"
echo Sony Playstation 2=>>"%GBC%\binimg.ini"
echo PC Engine CD=>>"%GBC%\binimg.ini"
echo TurboGrafx CD=>>"%GBC%\binimg.ini"
echo Sony PSP=>>"%GBC%\binimg.ini"
echo ----------=>>"%GBC%\binimg.ini"
echo -New Console-=>>"%GBC%\binimg.ini"
echo ----------=>>"%GBC%\binimg.ini"
set CURNTA=conselect.set



if exist "%GBC%\conselect.ini" set CURNTA=conselect.ini
for /f "delims=" %%a in ('type "%GBC%\%CURNTA%"') do (
echo.%%~a=>>"%GBC%\inbet.ini"
echo.%%~a=>>"%GBC%\cdimg.ini"
echo.%%~a=>>"%GBC%\dvdimg.ini"
echo.%%~a=>>"%GBC%\discimg.ini"
)
pushd "%GBC%"
for /f "delims=" %%a in ('dir /b/a-d "inbet.ini" "binimg.ini" "cdimg.ini" "dvdimg.ini" "discimg.ini"') do "%GBC%\fart.exe" "%%~nxa" = --remove
popd