if "%CVAREMU%"=="" for %%a in ("%CEMU%") do set CVAREMU=%%~a
if /i "%CVAREMU%"=="Atari800" set SHRTE=AT8E
if /i "%CVAREMU%"=="Akiko" set SHRTE=AKIKO
if /i "%CVAREMU%"=="Altirra" set SHRTE=ALTRA
if /i "%CVAREMU%"=="ArcEm" set SHRTE=ARCEM
if /i "%CVAREMU%"=="Arculator" set SHRTE=ARLTR
if /i "%CVAREMU%"=="Anex86" set SHRTE=ANEX
if /i "%CVAREMU%"=="ArcadePCLoader" set SHRTE=APCL
if /i "%CVAREMU%"=="AppleWin" set SHRTE=APLWIN
if /i "%CVAREMU%"=="atari++" set SHRTE=ATRI
if /i "%CVAREMU%"=="BatchScriptLauncher" set SHRTE=BATCHL
if /i "%CVAREMU%"=="BeebEm" set SHRTE=BEEBEM
if /i "%CVAREMU%"=="bsnes" set SHRTE=BSNS
if /i "%CVAREMU%"=="BlueMSX" set SHRTE=BMSX
if /i "%CVAREMU%"=="cps3emulator" set SHRTE=CPS3EMU
if /i "%CVAREMU%"=="Colem" set SHRTE=COLEM
if /i "%CVAREMU%"=="Demul" set SHRTE=DMUL
if /i "%CVAREMU%"=="DesMume" set SHRTE=DESMUME
if /i "%CVAREMU%"=="Dolphin" set SHRTE=DOLPH
if /i "%CVAREMU%"=="ElectrEm" set SHRTE=ELECEM
if /i "%CVAREMU%"=="em7" set SHRTE=EMSEV
if /i "%CVAREMU%"=="pcsxr" set SHRTE=PCSXR
if /i "%CVAREMU%"=="ePSXe" set SHRTE=EPSXE
if /i "%CVAREMU%"=="FinalBurnAlpha" set SHRTE=FBA
if /i "%CVAREMU%"=="Unz" set SHRTE=FMUNZ
if /i "%CVAREMU%"=="4DO" set SHRTE=FOURDO
if /i "%CVAREMU%"=="FlashPlayer" set SHRTE=FSHPL
if /i "%CVAREMU%"=="FreeDO" set SHRTE=FRDO
if /i "%CVAREMU%"=="FS-UAE" set SHRTE=FSUAE
if /i "%CVAREMU%"=="Fusion" set SHRTE=FUSN
if /i "%CVAREMU%"=="fceux" set SHRTE=FCEUX
if /i "%CVAREMU%"=="hatari" set SHRTE=HATARI
if /i "%CVAREMU%"=="Bliss" set SHRTE=INTV
if /i "%CVAREMU%"=="jum52" set SHRTE=JUM52
if /i "%CVAREMU%"=="Jagulator" set SHRTE=JAGLT
if /i "%CVAREMU%"=="jnes" set SHRTE=JNES
if /i "%CVAREMU%"=="jpcsp" set SHRTE=JPCSP
if /i "%CVAREMU%"=="jzintv" set SHRTE=JZINTV
if /i "%CVAREMU%"=="Kegs32" set SHRTE=KEGS
if /i "%CVAREMU%"=="M88" set SHRTE=M88
if /i "%CVAREMU%"=="m2emulator" set SHRTE=M2EMU
if /i "%CVAREMU%"=="Mednafen" set SHRTE=MEDN
if /i "%CVAREMU%"=="MagicEngine" set SHRTE=MENG
if /i "%CVAREMU%"=="Mame" set SHRTE=MAME
if /i "%CVAREMU%"=="Mess" set SHRTE=MESS
if /i "%CVAREMU%"=="DOSBox" set SHRTE=MSBOX
if /i "%CVAREMU%"=="Mugen" set SHRTE=MUGN
if /i "%CVAREMU%"=="Nebula" set SHRTE=NEBULA
if /i "%CVAREMU%"=="Neko" set SHRTE=NEKO
if /i "%CVAREMU%"=="neocd" set SHRTE=NEOCDEMU
if /i "%CVAREMU%"=="NeoRaine" set SHRTE=NEORAINE
if /i "%CVAREMU%"=="raine" set SHRTE=RAINE
if /i "%CVAREMU%"=="nestopia" set SHRTE=NESTP
if /i "%CVAREMU%"=="No$GBA" set SHRTE=NOGBA
if /i "%CVAREMU%"=="Nostalgia" set SHRTE=NOSTL
if /i "%CVAREMU%"=="NullDC" set SHRTE=NULLDC
if /i "%CVAREMU%"=="Ootake" set SHRTE=OOTK
if /i "%CVAREMU%"=="OpenMSX" set SHRTE=OPNMSX
if /i "%CVAREMU%"=="Pcsx2" set SHRTE=PCSX2
if /i "%CVAREMU%"=="PopCap" set SHRTE=PCAP
if /i "%CVAREMU%"=="Project64" set SHRTE=PJ64
if /i "%CVAREMU%"=="ParaJVE" set SHRTE=PJVE
if /i "%CVAREMU%"=="3DOplay" set SHRTE=PLAY3DO
if /i "%CVAREMU%"=="ProSystem" set SHRTE=PROSYS
if /i "%CVAREMU%"=="PPSSPP" set SHRTE=PSSP
if /i "%CVAREMU%"=="psx" set SHRTE=PSX
if /i "%CVAREMU%"=="ProjectTempest" set SHRTE=PTMPS
if /i "%CVAREMU%"=="raine" set SHRTE=RAINE
if /i "%CVAREMU%"=="ScummVM" set SHRTE=SCMVM
if /i "%CVAREMU%"=="SimCoupe" set SHRTE=SIMC
if /i "%CVAREMU%"=="snes9x" set SHRTE=SNES9X
if /i "%CVAREMU%"=="bgb" set SHRTE=BGB
if /i "%CVAREMU%"=="SNESGT" set SHRTE=SNESGT
if /i "%CVAREMU%"=="Supermodel" set SHRTE=SPRM3
if /i "%CVAREMU%"=="SSF" set SHRTE=SSF
if /i "%CVAREMU%"=="retroArch" set SHRTE=RTROA
if /i "%CVAREMU%"=="Steem" set SHRTE=STEEM
if /i "%CVAREMU%"=="Stella" set SHRTE=STLA
if /i "%CVAREMU%"=="FlashPlayer" set SHRTE=SWFPL
if /i "%CVAREMU%"=="TurboEngine" set SHRTE=TURBOE
if /i "%CVAREMU%"=="VirtualColeco" set SHRTE=VCOLEC
if /i "%CVAREMU%"=="VisualBoyAdvance" set SHRTE=VGBA
if /i "%CVAREMU%"=="WinVICE" set SHRTE=VICE
if /i "%CVAREMU%"=="xvic" set SHRTE=XVIC
if /i "%CVAREMU%"=="VirtualJaguar" set SHRTE=VJAG
if /i "%CVAREMU%"=="VirtuaNes" set SHRTE=VNES
if /i "%CVAREMU%"=="EMU7800" set SHRTE=VSVH
if /i "%CVAREMU%"=="CD-I" set SHRTE=WCDI
if /i "%CVAREMU%"=="WinArcadia" set SHRTE=WINARC
if /i "%CVAREMU%"=="WinAPE" set SHRTE=WINAPE
if /i "%CVAREMU%"=="WinUAE" set SHRTE=WINUAE
if /i "%CVAREMU%"=="WinX68k" set SHRTE=WINX68K
if /i "%CVAREMU%"=="XM6" set SHRTE=XM6
if /i "%CVAREMU%"=="XM7" set SHRTE=XM7
if /i "%CVAREMU%"=="X1turbo" set SHRTE=XTURB
if /i "%CVAREMU%"=="Zinc" set SHRTE=ZINC
if /i "%CVAREMU%"=="Zsnes" set SHRTE=ZSNS
if /i "%CVAREMU%"=="ZXSPIN" set SHRTE=ZXSpin