set SHRTN=
if /i "%CSTCONS%"=="%ACAN%" set SHRTN=ACAN
if /i "%CSTCONS%"=="%ACBBC%" set SHRTN=ACBBC
if /i "%CSTCONS%"=="%ACARC%" set SHRTN=ACARC
if /i "%CSTCONS%"=="%ACELE%" set SHRTN=ACELE
if /i "%CSTCONS%"=="%ADVV%" set SHRTN=ADVV
if /i "%CSTCONS%"=="%AMSGX%" set SHRTN=AMSGX
if /i "%CSTCONS%"=="%AMSTR%" set SHRTN=AMSTR
if /i "%CSTCONS%"=="%AMLG%" set SHRTN=AMLG
if /i "%CSTCONS%"=="%COLADM%" set SHRTN=COLADM
if /i "%CSTCONS%"=="%AMIGTV%" set SHRTN=AMIGTV
if /i "%CSTCONS%"=="%AMIG32%" set SHRTN=AMIG32
if /i "%CSTCONS%"=="%APL2E%" set SHRTN=APL2E
if /i "%CSTCONS%"=="%APL2GS%" set SHRTN=APL2GS
if /i "%CSTCONS%"=="%AQURS%" set SHRTN=AQURS
if /i "%CSTCONS%"=="%APFIM%" set SHRTN=APFIM
if /i "%CSTCONS%"=="%ARCD%" set SHRTN=ARCD
if /i "%CSTCONS%"=="%AT26%" set SHRTN=AT26
if /i "%CSTCONS%"=="%AT52%" set SHRTN=AT52
if /i "%CSTCONS%"=="%AT78%" set SHRTN=AT78
if /i "%CSTCONS%"=="%AT8B%" set SHRTN=AT8B
if /i "%CSTCONS%"=="%AT8H%" set SHRTN=AT8H
if /i "%CSTCONS%"=="%ATST%" set SHRTN=ATST
if /i "%CSTCONS%"=="%ATXE%" set SHRTN=ATXE
if /i "%CSTCONS%"=="%ATMS%" set SHRTN=ATMS
if /i "%CSTCONS%"=="%BALY%" set SHRTN=BALY
if /i "%CSTCONS%"=="%BWS%" set SHRTN=BWS
if /i "%CSTCONS%"=="%BWSC%" set SHRTN=BWSC
if /i "%CSTCONS%"=="%CAMIG%" set SHRTN=CAMIG
if /i "%CSTCONS%"=="%CDI%" set SHRTN=CDI
if /i "%CSTCONS%"=="%CHNF%" set SHRTN=CHNF
if /i "%CSTCONS%"=="%COM16%" set SHRTN=COM16
if /i "%CSTCONS%"=="%CM64%" set SHRTN=CM64
if /i "%CSTCONS%"=="%CMMAX%" set SHRTN=CMMAX
if /i "%CSTCONS%"=="%CMPET%" set SHRTN=CMPET
if /i "%CSTCONS%"=="%CLOOP%" set SHRTN=CLOOP
if /i "%CSTCONS%"=="%CAS1K%" set SHRTN=CAS1K
if /i "%CSTCONS%"=="%CAS2K%" set SHRTN=CAS2K
if /i "%CSTCONS%"=="%COLEC%" set SHRTN=COLEC
if /i "%CSTCONS%"=="%CPS%" set SHRTN=CPS
if /i "%CSTCONS%"=="%CPS2%" set SHRTN=CPS2
if /i "%CSTCONS%"=="%CPS3%" set SHRTN=CPS3
if /i "%CSTCONS%"=="%EMARC%" set SHRTN=EMARC
if /i "%CSTCONS%"=="%ENTP64%" set SHRTN=ENTP64
if /i "%CSTCONS%"=="%ENTP128%" set SHRTN=ENTP128
if /i "%CSTCONS%"=="%DAPHN%" set SHRTN=DAPHN
if /i "%CSTCONS%"=="%DRAG32%" set SHRTN=DRAG32
if /i "%CSTCONS%"=="%FLASH%" set SHRTN=FLASH
if /i "%CSTCONS%"=="%FM7%" set SHRTN=FM7
if /i "%CSTCONS%"=="%FMTOWNS%" set SHRTN=FMTOWNS
if /i "%CSTCONS%"=="%GACOM%" set SHRTN=GACOM
if /i "%CSTCONS%"=="%GALCO%" set SHRTN=GALCO
if /i "%CSTCONS%"=="%HIKARU%" set SHRTN=HIKARU
if /i "%CSTCONS%"=="%INTEL%" set SHRTN=INTEL
if /i "%CSTCONS%"=="%IMAG%" set SHRTN=IMAG
if /i "%CSTCONS%"=="%JAGCD%" set SHRTN=JAGCD
if /i "%CSTCONS%"=="%JAG%" set SHRTN=JAG
if /i "%CSTCONS%"=="%JUPA%" set SHRTN=JUPA
if /i "%CSTCONS%"=="%LYNX%" set SHRTN=LYNX
if /i "%CSTCONS%"=="%MDUC%" set SHRTN=MDUC
if /i "%CSTCONS%"=="%MITAN%" set SHRTN=MITAN
if /i "%CSTCONS%"=="%MO5%" set SHRTN=MO5
if /i "%CSTCONS%"=="%MSDS%" set SHRTN=MSDS
if /i "%CSTCONS%"=="%MACINT%" set SHRTN=MACINT
if /i "%CSTCONS%"=="%MTX%" set SHRTN=MTX
if /i "%CSTCONS%"=="%MSX%" set SHRTN=MSX
if /i "%CSTCONS%"=="%MSX2%" set SHRTN=MSX2
if /i "%CSTCONS%"=="%MSXTR%" set SHRTN=MSXTR
if /i "%CSTCONS%"=="%MZ7%" set SHRTN=MZ7
if /i "%CSTCONS%"=="%MZ8%" set SHRTN=MZ8
if /i "%CSTCONS%"=="%N64%" set SHRTN=N64
if /i "%CSTCONS%"=="%NAOMI%" set SHRTN=NAOMI
if /i "%CSTCONS%"=="%NEOPKT%" set SHRTN=NEOPKT
if /i "%CSTCONS%"=="%NEOPKTC%" set SHRTN=NEOPKTC
if /i "%CSTCONS%"=="%NEOGE%" set SHRTN=NEOGE
if /i "%CSTCONS%"=="%NEOCD%" set SHRTN=NEOCD
if /i "%CSTCONS%"=="%NDS%" set SHRTN=NDS
if /i "%CSTCONS%"=="%NVB%" set SHRTN=NVB
if /i "%CSTCONS%"=="%NGC%" set SHRTN=NGC
if /i "%CSTCONS%"=="%NGB%" set SHRTN=NGB
if /i "%CSTCONS%"=="%NGBC%" set SHRTN=NGBC
if /i "%CSTCONS%"=="%NGBA%" set SHRTN=NGBA
if /i "%CSTCONS%"=="%NES%" set SHRTN=NES
if /i "%CSTCONS%"=="%NFAM%" set SHRTN=NFAM
if /i "%CSTCONS%"=="%NSATL%" set SHRTN=NSATL
if /i "%CSTCONS%"=="%ODYS%" set SHRTN=ODYS
if /i "%CSTCONS%"=="%ODYS2%" set SHRTN=ODYS2
if /i "%CSTCONS%"=="%ODYS3%" set SHRTN=ODYS3
if /i "%CSTCONS%"=="%P3DO%" set SHRTN=P3DO
if /i "%CSTCONS%"=="%PC6K%" set SHRTN=PC6K
if /i "%CSTCONS%"=="%PC88%" set SHRTN=PC88
if /i "%CSTCONS%"=="%PC88VA%" set SHRTN=PC88VA
if /i "%CSTCONS%"=="%PC98%" set SHRTN=PC98
if /i "%CSTCONS%"=="%PCAP%" set SHRTN=PCAP
if /i "%CSTCONS%"=="%PCECD%" set SHRTN=PCECD
if /i "%CSTCONS%"=="%PCENG%" set SHRTN=PCENG
if /i "%CSTCONS%"=="%PCFX%" set SHRTN=PCFX
if /i "%CSTCONS%"=="%PCJR%" set SHRTN=PCJR
if /i "%CSTCONS%"=="%PPC2K%" set SHRTN=PPC2K
if /i "%CSTCONS%"=="%PVG5K%" set SHRTN=PVG5K
if /i "%CSTCONS%"=="%PVG74%" set SHRTN=PVG74
if /i "%CSTCONS%"=="%POCKS%" set SHRTN=POCKS
if /i "%CSTCONS%"=="%PS1%" set SHRTN=PS1
if /i "%CSTCONS%"=="%PS2%" set SHRTN=PS2
if /i "%CSTCONS%"=="%PSVITA%" set SHRTN=PSVITA
if /i "%CSTCONS%"=="%PS4%" set SHRTN=PS4
if /i "%CSTCONS%"=="%PS3%" set SHRTN=PS3
if /i "%CSTCONS%"=="%PSP%" set SHRTN=PSP
if /i "%CSTCONS%"=="%OBOR%" set SHRTN=OBOR
if /i "%CSTCONS%"=="%ORIC%" set SHRTN=ORIC
if /i "%CSTCONS%"=="%PV1K%" set SHRTN=PV1K
if /i "%CSTCONS%"=="%PV2K%" set SHRTN=PV2K
if /i "%CSTCONS%"=="%RCAS2%" set SHRTN=RCAS2
if /i "%CSTCONS%"=="%SAMC%" set SHRTN=SAMC
if /i "%CSTCONS%"=="%SCUM%" set SHRTN=SCUM
if /i "%CSTCONS%"=="%SCAS%" set SHRTN=SCAS
if /i "%CSTCONS%"=="%SEG1K%" set SHRTN=SEG1K
if /i "%CSTCONS%"=="%SEG3K%" set SHRTN=SEG3K
if /i "%CSTCONS%"=="%SEGSF%" set SHRTN=SEGSF
if /i "%CSTCONS%"=="%SEG7K%" set SHRTN=SEG7K
if /i "%CSTCONS%"=="%SEGAG%" set SHRTN=SEGAG
if /i "%CSTCONS%"=="%SEGAP%" set SHRTN=SEGAP
if /i "%CSTCONS%"=="%SEGAMD%" set SHRTN=SEGAMD
if /i "%CSTCONS%"=="%SEGMS%" set SHRTN=SEGMS
if /i "%CSTCONS%"=="%TOMYT%" set SHRTN=TOMYT
if /i "%CSTCONS%"=="%MO5%" set SHRTN=MO5
if /i "%CSTCONS%"=="%TO7%" set SHRTN=TO7
if /i "%CSTCONS%"=="%TO8%" set SHRTN=TO8
if /i "%CSTCONS%"=="%EXL1H%" set SHRTN=EXL1H
if /i "%CSTCONS%"=="%INTFC%" set SHRTN=INTFC
if /i "%CSTCONS%"=="%CMPLNX%" set SHRTN=CMPLNX
if /i "%CSTCONS%"=="%SEGDC%" set SHRTN=SEGDC
if /i "%CSTCONS%"=="%SEGG%" set SHRTN=SEGG
if /i "%CSTCONS%"=="%SEGCD%" set SHRTN=SEGCD
if /i "%CSTCONS%"=="%SEGM2%" set SHRTN=SEGM2
if /i "%CSTCONS%"=="%SEGM3%" set SHRTN=SEGM3
if /i "%CSTCONS%"=="%SFAM%" set SHRTN=SFAM
if /i "%CSTCONS%"=="%SG32X%" set SHRTN=SG32X
if /i "%CSTCONS%"=="%SGFX%" set SHRTN=SGFX
if /i "%CSTCONS%"=="%SEGMCD%" set SHRTN=SEGMCD
if /i "%CSTCONS%"=="%SNES%" set SHRTN=SNES
if /i "%CSTCONS%"=="%SNQL%" set SHRTN=SNQL
if /i "%CSTCONS%"=="%SORD%" set SHRTN=SORD
if /i "%CSTCONS%"=="%SPECV%" set SHRTN=SPECV
if /i "%CSTCONS%"=="%SSAT%" set SHRTN=SSAT
if /i "%CSTCONS%"=="%SSTV%" set SHRTN=SSTV
if /i "%CSTCONS%"=="%SHRPX1%" set SHRTN=SHRPX1
if /i "%CSTCONS%"=="%SVIS%" set SHRTN=SVIS
if /i "%CSTCONS%"=="%SUPRGB%" set SHRTN=SUPRGB
if /i "%CSTCONS%"=="%TAITX%" set SHRTN=TAITX
if /i "%CSTCONS%"=="%TG16%" set SHRTN=TG16
if /i "%CSTCONS%"=="%TGCD%" set SHRTN=TGCD
if /i "%CSTCONS%"=="%TOUHU%" set SHRTN=TOUHU
if /i "%CSTCONS%"=="%TRIF%" set SHRTN=TRIF
if /i "%CSTCONS%"=="%VECTX%" set SHRTN=VECTX
if /i "%CSTCONS%"=="%VC4K%" set SHRTN=VC4K
if /i "%CSTCONS%"=="%VC20%" set SHRTN=VC20
if /i "%CSTCONS%"=="%VCRV%" set SHRTN=VCRV
if /i "%CSTCONS%"=="%VLAS2%" set SHRTN=VLAS2
if /i "%CSTCONS%"=="%VLAS3%" set SHRTN=VLAS3
if /i "%CSTCONS%"=="%X360%" set SHRTN=X360
if /i "%CSTCONS%"=="%X68K%" set SHRTN=X68K
if /i "%CSTCONS%"=="%XBX%" set SHRTN=XBX
if /i "%CSTCONS%"=="%WII%" set SHRTN=WII
if /i "%CSTCONS%"=="%WIIU%" set SHRTN=WIIU
if /i "%CSTCONS%"=="%WIN32%" set SHRTN=WIN32
if /i "%CSTCONS%"=="%ZXSP%" set SHRTN=ZXSP
if /i "%CSTCONS%"=="%ZX81%" set SHRTN=ZX81