for %%a in ("Apple 1") do set APL1=%%~a
for %%a in ("Apple III") do set APL3=%%~a
for %%a in ("Apple Macintosh CD") do set APLMAC=%%~a
for %%a in ("Apple Macintosh") do set APLMAC=%%~a
for %%a in ("Apple Lisa") do set APLISA=%%~a
for %%a in ("Applied Technology MicroBee") do set MICROB=%%~a
for %%a in ("Altos Computer Systems ACS-186, 586 & 986") do set ALTCS=%%~a
for %%a in ("Bandai Playdia CD") do set BPLYD=%%~a
for %%a in ("Bandai Playdia") do set BPLYD=%%~a
for %%a in ("Bondwell 12") do set BONDW12=%%~a
for %%a in ("Cybiko Cybiko") do set CYBIKO=%%~a
for %%a in ("DEC PDP-1") do set DECP1=%%~a
for %%a in ("DEC PDP-7") do set DECP7=%%~a
for %%a in ("DEC PDP-8") do set DECP8=%%~a
for %%a in ("DEC PDP-9") do set DECP9=%%~a
for %%a in ("Tesla PMD 85") do set TESPMD=%%~a
for %%a in ("Hewlett-Packard HP48") do set HP48=%%~a
for %%a in ("Hewlett-Packard HP49") do set HP49=%%~a
for %%a in ("DEC PDP-10") do set DECPX=%%~a
for %%a in ("DEC PDP-11") do set DECPXI=%%~a
for %%a in ("DEC PDP-12") do set DECPXII=%%~a
for %%a in ("Elektronika BK-0010-0011M") do set ELEKBK11M=%%~a
for %%a in ("Elektronika BK-0011-411") do set ELEKBK4M=%%~a
for %%a in ("Elektronska Industrija Nis PECOM 32 & 64") do set ELEKINSP=%%~a
for %%a in ("Commodore MAX Machine & VIC10") do set COMMVIC=%%~a
for %%a in ("Front Fareast Magic Drive") do set FRMAGD=%%~a
for %%a in ("Tatung Einstein TC-01") do set TATEIN=%%~a
for %%a in ("Fuji Photo Film Magic Drive") do set FUJIMD=%%~a
for %%a in ("Fuji Photo Film FUJIC") do set FUJIC=%%~a
for %%a in ("Canon Cat") do set CANCAT=%%~a
for %%a in ("Bondwell 2") do set BONDW2=%%~a
for %%a in ("Camputers Lynx") do set CAMPLNX=%%~a
for %%a in ("Galaksija Galaksija") do set GALAK=%%~a
for %%a in ("Dick Smith System 80") do set DSMS80=%%~a
for %%a in ("EACA EG2000 Colour Genie") do set EACACG=%%~a
for %%a in ("ETL Mark II") do set ETLM2=%%~a
for %%a in ("ETL Mark IV") do set ETLM4=%%~a
for %%a in ("Kaypro II") do set KAYPR=%%~a
for %%a in ("Infocom Z-Machine") do set INFZM=%%~a
for %%a in ("Interact Family Computer") do set INFCOM=%%~a
for %%a in ("Exelvision Exeltel") do set EXETEL=%%~a
for %%a in ("Exelvision EXL100") do set EXL100=%%~a
for %%a in ("Keio University K-1") do set KEIO=%%~a
for %%a in ("Incredible Technologies Eagle CD") do set INCEAG=%%~a
for %%a in ("Konami Bemani System 573 Analog") do set KONANL=%%~a
for %%a in ("Konami Bemani System 573 Digital") do set KONDIG=%%~a
for %%a in ("Konami Bemani System 573") do set KON573=%%~a
for %%a in ("Exidy Sorcerer") do set ESORCER=%%~a
for %%a in ("Epson PX-8, HC-88 & Geneva") do set EPXGEN=%%~a
for %%a in ("Franklin ACE 100") do set FRACE=%%~a
for %%a in ("HomeLab BraiLab") do set BRAILB=%%~a
for %%a in ("HomeLab HomeLab") do set HOMLAB=%%~a
for %%a in ("Hewlett-Packard HP4") do set HPHP4=%%~a
for %%a in ("IBM PC Compatibles") do set IBMPCMP=%%~a
for %%a in ("iQue Player") do set IQUE=%%~a
for %%a in ("Luxor ABC 80") do set LUXA80=%%~a
for %%a in ("Spectravideo SVI-318 & SVI-328") do set SPCTSVI=%%~a
for %%a in ("Tandy Radio Shack TRS-80 Color Computer") do set TRS80=%%~a
for %%a in ("Technosys Aamber Pegasus") do set AMPEG=%%~a
for %%a in ("Altos Computer Systems Series 5") do set ALTS5=%%~a
for %%a in ("Texas Instruments CC-40") do set TICC40=%%~a
for %%a in ("Texas Instruments TI-73") do set TI73=%%~a
for %%a in ("Texas Instruments TI-80") do set TI80=%%~a
for %%a in ("Texas Instruments TI-81") do set TI81=%%~a
for %%a in ("Texas Instruments TI-82") do set TI82=%%~a
for %%a in ("Texas Instruments TI-83") do set TI83=%%~a
for %%a in ("Texas Instruments TI-86") do set TI86=%%~a
for %%a in ("Texas Instruments TI-89") do set TI89=%%~a
for %%a in ("Texas Instruments TI-92") do set TI92=%%~a
for %%a in ("Texas Instruments TI-99") do set TI99=%%~a
for %%a in ("Altos Computer Systems ACS-8000") do set ALTACS8=%%~a
for %%a in ("Texas Instruments TI-99 4A") do set TI994A=%%~a
for %%a in ("University of Cambridge EDSAC") do set EDSAC=%%~a
for %%a in ("VTech V.Flash Home Edutainment System") do set VFLASH=%%~a
for %%a in ("Tiki Data Kontiki-100 & Tiki-100") do set TIKICON=%%~a
for %%a in ("Tsukuda Original Othello Multivision") do set OTHMULT=%%~a
for %%a in ("University of Tokyo PC-1") do set TOKYO=%%~a
for %%a in ("Thomson TO9+") do set TO9=%%~a
for %%a in ("Wang VS") do set WANGVS=%%~a
for %%a in ("Videoton TV-Computer") do set VIDTVCOM=%%~a
for %%a in ("Tomy KISS-Site") do set TOMYKISS=%%~a
for %%a in ("VM Labs Nuon") do set NUON=%%~a
for %%a in ("ZAPiT Games Game Wave Family Entertainment System") do set ZAPIT=%%~a
for %%a in ("Matsushita National JR 200") do set MATSJR2=%%~a
for %%a in ("Matsushita National JR-100") do set MATSJR1=%%~a
for %%a in ("Mattel HyperScan") do set HPSCAN=%%~a
for %%a in ("Memorex Video Information System") do set MEMVIS=%%~a
for %%a in ("Microkey Primo") do set MICPRO=%%~a
for %%a in ("MITS Altair 8800") do set MITSA8=%%~a
for %%a in ("Multi-format") do set MULTFRMT=%%~a
for %%a in ("Luxor ABC 800") do set LUXA800=%%~a
for %%a in ("Matra Hachette Alice 32") do set ALICE32=%%~a
for %%a in ("Nascom I & II") do set NASCOM=%%~a
for %%a in ("Nintendo Pokemon Mini") do set NPOKE=%%~a
for %%a in ("OCC Osborne 1 & Osborne Executive") do set OSBRN=%%~a
for %%a in ("PTC Sol Terminal Computer SOL-20") do set PTCSOL=%%~a
for %%a in ("OpenPandora Pandora") do set OPENPAN=%%~a
for %%a in ("PEL Varazdin Orao") do set ORAO=%%~a
for %%a in ("Sega WonderMega CD") do set SEGWM=%%~a
for %%a in ("Sega WonderMega") do set SEGWM=%%~a
for %%a in ("Sharp MZ-700") do set SHRPMZ7=%%~a
for %%a in ("Sharp MZ-00") do set SHRPMZ=%%~a
for %%a in ("Sega Visual Memory System") do set SEGVMS=%%~a
for %%a in ("Radio-86RK") do set RAD86=%%~a
for %%a in ("RCA Chip-8") do set RCACHP8=%%~a
for %%a in ("RM Nimbus PC") do set NIMBUS=%%~a
for %%a in ("Robotron HC900, KC85 2, KC85 3 & KC85 4") do set RBTRON=%%~a
for %%a in ("Robotron KC Compact") do set RBTRNKC=%%~a
for %%a in ("Robotron Z1013") do set RBTRONZ1=%%~a
for %%a in ("Robotron Z9001 & KC85 1") do set RBTRONZ9=%%~a
for %%a in ("Visual Technology Visual 1050") do set VIS10=%%~a
for %%a in ("SABA Videoplay") do set SVIDP=%%~a
for %%a in ("Prologica") do set PROLGC=%%~a
for %%a in ("NCR Decision Mate V") do set DECMV=%%~a
for %%a in ("Luxor Video Entertainment System") do set LUXVES=%%~a
for %%a in ("Casio CFX-9850") do set CASCFX=%%~a
for %%a in ("Radio-86RK Mikro-80") do set RADMIK8=%%~a
for %%a in ("Radica Arcade Legends & Play TV Legends") do set RADLEG=%%~a
for %%a in ("Radio-86RK Apogej BK-01") do set RADAP=%%~a
for %%a in ("Radio-86RK YuT-88") do set RADYUT=%%~a
for %%a in ("Radio-86RK Radio-86RK") do set RAD86RK=%%~a
for %%a in ("Cybiko Xtreme") do set CYBEX=%%~a
for %%a in ("RCA Superchip") do set RCASUP=%%~a
for %%a in ("Luxor backdrops Entertainment System") do set LUXBACK=%%~a
for %%a in ("Pioneer LaserActive") do set PIONLA=%%~a
for %%a in ("Radio-86RK Mikrosha") do set RADMIKRO=%%~a
for %%a in ("Radio-86RK Partner-01.01") do set RADPART=%%~a
for %%a in ("Sharp MZ-800 & MZ-1500") do set SHRPMZ8=%%~a