pushd "%GBC%\net\%XPROF%\%CSTLNCH%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT1] "%P1SET1BUT1%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT2] "%P1SET1BUT2%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT3] "%P1SET1BUT3%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT4] "%P1SET1BUT4%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT5] "%P1SET1BUT5%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT6] "%P1SET1BUT6%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT7] "%P1SET1BUT7%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT8] "%P1SET1BUT8%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT9] "%P1SET1BUT9%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUT10] "%P1SET1BUT10%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT1] "%P1SET2BUT1%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT2] "%P1SET2BUT2%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT3] "%P1SET2BUT3%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT4] "%P1SET2BUT4%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT5] "%P1SET2BUT5%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT6] "%P1SET2BUT6%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT7] "%P1SET2BUT7%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT8] "%P1SET2BUT8%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT9] "%P1SET2BUT9%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUT10] "%P1SET2BUT10%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT1] "%P1SET3BUT1%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT2] "%P1SET3BUT2%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT3] "%P1SET3BUT3%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT4] "%P1SET3BUT4%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT5] "%P1SET3BUT5%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT6] "%P1SET3BUT6%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT7] "%P1SET3BUT7%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT8] "%P1SET3BUT8%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT9] "%P1SET3BUT9%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUT10] "%P1SET3BUT10%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS1] "%P1SET1BUTSS1%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS2] "%P1SET1BUTSS2%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS3] "%P1SET1BUTSS3%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS4] "%P1SET1BUTSS4%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS5] "%P1SET1BUTSS5%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS6] "%P1SET1BUTSS6%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS7] "%P1SET1BUTSS7%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS8] "%P1SET1BUTSS8%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS9] "%P1SET1BUTSS9%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1BUTSS10] "%P1SET1BUTSS10%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS1] "%P1SET2BUTSS1%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS2] "%P1SET2BUTSS2%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS3] "%P1SET2BUTSS3%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS4] "%P1SET2BUTSS4%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS5] "%P1SET2BUTSS5%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS6] "%P1SET2BUTSS6%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS7] "%P1SET2BUTSS7%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS8] "%P1SET2BUTSS8%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS9] "%P1SET2BUTSS9%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2BUTSS10] "%P1SET2BUTSS10%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS1] "%P1SET3BUTSS1%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS2] "%P1SET3BUTSS2%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS3] "%P1SET3BUTSS3%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS4] "%P1SET3BUTSS4%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS5] "%P1SET3BUTSS5%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS6] "%P1SET3BUTSS6%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS7] "%P1SET3BUTSS7%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS8] "%P1SET3BUTSS8%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS9] "%P1SET3BUTSS9%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3BUTSS10] "%P1SET3BUTSS10%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1PADUP] "%P1SET1PADUP%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1PADDOWN] "%P1SET1PADDOWN%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1PADLEFT] "%P1SET1PADLEFT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1PADRIGHT] "%P1SET1PADRIGHT%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2PADUP] "%P1SET2PADUP%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2PADDOWN] "%P1SET2PADDOWN%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2PADLEFT] "%P1SET2PADLEFT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2PADRIGHT] "%P1SET2PADRIGHT%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3PADUP] "%P1SET3PADUP%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3PADDOWN] "%P1SET3PADDOWN%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3PADLEFT] "%P1SET3PADLEFT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3PADRIGHT] "%P1SET3PADRIGHT%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1STICKUP] "%P1SET1STICKUP%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1STICKDOWN] "%P1SET1STICKDOWN%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1STICKLEFT] "%P1SET1STICKLEFT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1STICKRIGHT] "%P1SET1STICKRIGHT%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2STICKUP] "%P1SET2STICKUP%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2STICKDOWN] "%P1SET2STICKDOWN%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2STICKLEFT] "%P1SET2STICKLEFT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2STICKRIGHT] "%P1SET2STICKRIGHT%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3STICKUP] "%P1SET3STICKUP%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3STICKDOWN] "%P1SET3STICKDOWN%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3STICKLEFT] "%P1SET3STICKLEFT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3STICKRIGHT] "%P1SET3STICKRIGHT%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1TRIGRIGHT] "%P1SET1TRIGRIGHT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET1TRIGLEFT] "%P1SET1TRIGLEFT%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2TRIGRIGHT] "%P1SET2TRIGRIGHT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET2TRIGLEFT] "%P1SET2TRIGLEFT%"

"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3TRIGRIGHT] "%P1SET3TRIGRIGHT%"
"%GBC%\fart.exe" "Player1.xpadderprofile" [SET3TRIGLEFT] "%P1SET3TRIGLEFT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT1] "%P2SET1BUT1%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT2] "%P2SET1BUT2%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT3] "%P2SET1BUT3%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT4] "%P2SET1BUT4%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT5] "%P2SET1BUT5%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT6] "%P2SET1BUT6%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT7] "%P2SET1BUT7%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT8] "%P2SET1BUT8%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT9] "%P2SET1BUT9%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUT10] "%P2SET1BUT10%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT1] "%P2SET2BUT1%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT2] "%P2SET2BUT2%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT3] "%P2SET2BUT3%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT4] "%P2SET2BUT4%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT5] "%P2SET2BUT5%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT6] "%P2SET2BUT6%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT7] "%P2SET2BUT7%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT8] "%P2SET2BUT8%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT9] "%P2SET2BUT9%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUT10] "%P2SET2BUT10%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT1] "%P2SET3BUT1%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT2] "%P2SET3BUT2%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT3] "%P2SET3BUT3%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT4] "%P2SET3BUT4%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT5] "%P2SET3BUT5%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT6] "%P2SET3BUT6%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT7] "%P2SET3BUT7%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT8] "%P2SET3BUT8%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT9] "%P2SET3BUT9%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUT10] "%P2SET3BUT10%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS1] "%P2SET1BUTSS1%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS2] "%P2SET1BUTSS2%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS3] "%P2SET1BUTSS3%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS4] "%P2SET1BUTSS4%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS5] "%P2SET1BUTSS5%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS6] "%P2SET1BUTSS6%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS7] "%P2SET1BUTSS7%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS8] "%P2SET1BUTSS8%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS9] "%P2SET1BUTSS9%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1BUTSS10] "%P2SET1BUTSS10%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS1] "%P2SET2BUTSS1%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS2] "%P2SET2BUTSS2%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS3] "%P2SET2BUTSS3%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS4] "%P2SET2BUTSS4%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS5] "%P2SET2BUTSS5%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS6] "%P2SET2BUTSS6%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS7] "%P2SET2BUTSS7%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS8] "%P2SET2BUTSS8%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS9] "%P2SET2BUTSS9%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2BUTSS10] "%P2SET2BUTSS10%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS1] "%P2SET3BUTSS1%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS2] "%P2SET3BUTSS2%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS3] "%P2SET3BUTSS3%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS4] "%P2SET3BUTSS4%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS5] "%P2SET3BUTSS5%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS6] "%P2SET3BUTSS6%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS7] "%P2SET3BUTSS7%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS8] "%P2SET3BUTSS8%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS9] "%P2SET3BUTSS9%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3BUTSS10] "%P2SET3BUTSS10%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1PADUP] "%P2SET1PADUP%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1PADDOWN] "%P2SET1PADDOWN%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1PADLEFT] "%P2SET1PADLEFT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1PADRIGHT] "%P2SET1PADRIGHT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2PADUP] "%P2SET2PADUP%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2PADDOWN] "%P2SET2PADDOWN%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2PADLEFT] "%P2SET2PADLEFT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2PADRIGHT] "%P2SET2PADRIGHT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3PADUP] "%P2SET3PADUP%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3PADDOWN] "%P2SET3PADDOWN%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3PADLEFT] "%P2SET3PADLEFT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3PADRIGHT] "%P2SET3PADRIGHT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1STICKUP] "%P2SET1STICKUP%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1STICKDOWN] "%P2SET1STICKDOWN%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1STICKLEFT] "%P2SET1STICKLEFT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1STICKRIGHT] "%P2SET1STICKRIGHT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2STICKUP] "%P2SET2STICKUP%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2STICKDOWN] "%P2SET2STICKDOWN%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2STICKLEFT] "%P2SET2STICKLEFT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2STICKRIGHT] "%P2SET2STICKRIGHT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3STICKUP] "%P2SET3STICKUP%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3STICKDOWN] "%P2SET3STICKDOWN%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3STICKLEFT] "%P2SET3STICKLEFT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3STICKRIGHT] "%P2SET3STICKRIGHT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1TRIGRIGHT] "%P2SET1TRIGRIGHT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET1TRIGLEFT] "%P2SET1TRIGLEFT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2TRIGRIGHT] "%P2SET2TRIGRIGHT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET2TRIGLEFT] "%P2SET2TRIGLEFT%"

"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3TRIGRIGHT] "%P2SET3TRIGRIGHT%"
"%GBC%\fart.exe" "Player2.xpadderprofile" [SET3TRIGLEFT] "%P2SET3TRIGLEFT%"
popd	